### ISSUE TITLE
`:mirrors` section not picked up from `profiles.clj`

### ISSUE THREAD

**Issue by gergoerdi** [technomancy/leiningen#2057] opened 2016-01-03 13:34 UTC
As documented in [this StackOverflow question](http://stackoverflow.com/q/34573135/477476), the `:mirrors` section isn't picked up from `~/.lein/profiles.clj`'s `:user` profile, only from the individual `project.clj` files.

**Comment by glts** [comment] 2019-05-31 17:19
This looks like a duplicate of #1722.

**Closed** 2019-06-20 16:33 UTC
Labels: bug
