### ISSUE TITLE
Failure launching repl

### ISSUE THREAD

**Issue by LennyPu** [technomancy/leiningen#2506] opened 2018-12-13 13:49 UTC
Exception in thread "Thread-1" java.lang.AssertionError: Assert failed: transport-fn
        at nrepl.core$connect.invokeStatic(core.clj:168)
        at nrepl.core$connect.doInvoke(core.clj:168)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at nrepl.ack$send_ack.invokeStatic(ack.clj:45)
        at nrepl.ack$send_ack.invoke(ack.clj:41)
        at nrepl.server$start_server.invokeStatic(server.clj:146)
        at nrepl.server$start_server.doInvoke(server.clj:105)
        at clojure.lang.RestFn.invoke(RestFn.java:1096)
        at user$eval747.invokeStatic(NO_SOURCE_FILE:0)
        at user$eval747.invoke(NO_SOURCE_FILE)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.eval(Compiler.java:6890)
        at clojure.core$eval.invokeStatic(core.clj:3105)
        at clojure.core$eval.invoke(core.clj:3101)
        at leiningen.core.eval$fn__4211.invokeStatic(eval.clj:343)
        at leiningen.core.eval$fn__4211.invoke(eval.clj:333)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:367)
        at leiningen.core.eval$eval_in_project.invoke(eval.clj:357)
        at leiningen.repl$server$fn__5985.invoke(repl.clj:276)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:650)
        at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
REPL server launch timed out.

**Comment by LennyPu** [comment] 2018-12-13 13:56
windows10

**Comment by LennyPu** [comment] 2018-12-13 13:59
Leiningen 2.8.2 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM
windows10

**Comment by amybruno** [comment] 2018-12-13 14:23
same issue here

Leiningen 2.8.2 on Java 1.8.0_192 OpenJDK 64-Bit Server VM
arch linux

**Comment by petrounias** [comment] 2018-12-13 14:51
same

Leiningen 2.8.2 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM
macOS 10.12.6

**Comment by Kejia** [comment] 2018-12-13 16:38
same

> $ lein version
> Leiningen 2.8.2 on Java 1.8.0_192 Java HotSpot(TM) 64-Bit Server VM
> $ sw_vers                                                                                                                                                                                   11:37:18
> ProductName:	Mac OS X
> ProductVersion:	10.14.2
> BuildVersion:	18C54

**Comment by technomancy** [comment] 2018-12-13 18:39
This is a duplicate of #2497 which is fixed on master, but I'll leave it open until 2.8.3 is released so people have an easier time finding it.

**Comment by bbatsov** [comment] 2018-12-14 08:50
For completeness I'll mention the workarounds here as well:

a) Run lein from `master` (or downgrade it to 2.8.1 for now).

b) Put `[nrepl "0.5.3"]` in your `profiles.clj`.

**Comment by mrojasb2000** [comment] 2018-12-14 18:37
I have installed lein via Homebrew, but same error on Mac OS Mojave. 
Leiningen 2.8.2 on Java 1.8.0_181 Java HotSpot(TM) 64-Bit Server VM
❯ lein repl
Exception in thread "Thread-1" java.lang.AssertionError: Assert failed: transport-fn
	at nrepl.core$connect.invokeStatic(core.clj:168)
	at nrepl.core$connect.doInvoke(core.clj:168)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at nrepl.ack$send_ack.invokeStatic(ack.clj:45)
	at nrepl.ack$send_ack.invoke(ack.clj:41)
	at nrepl.server$start_server.invokeStatic(server.clj:146)
	at nrepl.server$start_server.doInvoke(server.clj:105)
	at clojure.lang.RestFn.invoke(RestFn.java:1096)
	at user$eval747.invokeStatic(NO_SOURCE_FILE:0)
	at user$eval747.invoke(NO_SOURCE_FILE)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6890)
	at clojure.core$eval.invokeStatic(core.clj:3105)
	at clojure.core$eval.invoke(core.clj:3101)
	at leiningen.core.eval$fn__4211.invokeStatic(eval.clj:343)
	at leiningen.core.eval$fn__4211.invoke(eval.clj:333)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at leiningen.core.eval$eval_in_project.invokeStatic(eval.clj:367)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:357)
	at leiningen.repl$server$fn__5985.invoke(repl.clj:276)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)

How to downgrade with Homebrew?

Thanks

**Comment by Kejia** [comment] 2018-12-14 20:14
@mrojasb2000 

> $ brew unlink leiningen 2.8.2
> $ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/9f86a002964fcb30fa7ef45616173dba46a2f070/Formula/leiningen.rb
> $ lein version

**Comment by technomancy** [comment] 2018-12-15 01:43
Going to close this out as 2.8.3 is now out.

**Closed by technomancy** 2018-12-15 01:43 UTC

**Comment by mrojasb2000** [comment] 2018-12-15 01:51
Excellent, thanks.
