### ISSUE TITLE
Pass to version 2.5.2 (Windowns install problem)

### ISSUE THREAD

**Issue by ivanpierre** [technomancy/leiningen#1841] opened 2015-02-24 09:07 UTC
I have often to explain Windows' users how to get and patch the 5.2.5 version of lein.bat file according to them to be able to install Leiningen... ;)

It's only to get the last version of .bat (not the one pointed to by the install page) and change the version to 2.5.1. But it's a little complicated for some people. :D

If the version 2.5.2 is still not stable, perhaps put a temporary link to a corrected file.

Thanks

**Comment by hyPiRion** [comment] 2015-02-24 11:48
Is this related to #1800? I was under the impression that 2.5.1 fixed the biggest issues with lein.bat from 2.5.0, but perhaps I am mistaken. How does this work with, say, leiningen-win-installer? Anyone else familiar with these issues?

We'd have to fix a couple of issues before releasing 2.5.2 (perhaps most notably #1746), but I can attempt to focus more on fixing issues for a new release if that's warranted.

Here's a corrected file, btw: https://gist.githubusercontent.com/hyPiRion/e1dac524a25251398bfd/raw/3e03d114dc74792a3c6944bd06d58e87ab4bca6f/lein.bat

**Comment by ivanpierre** [comment] 2015-02-24 20:21
Ok, The zip priblem was resolved for 2.5.1, but the lein.bat was changed after the release. So the present daily lein.bat is good, but is connected to 2.5.2-SNAPSHOT, the one for 2.5.1 (https://github.com/technomancy/leiningen/blob/2.5.1/bin/lein.bat) is still connected to the jar.

For the other installer, I've no contact with the installer and I think looking at the code he takes an old version of lein.bat and make a lein upgrade, so it will fail for now. I'll test when situation stabilize. For the chocolaty install, I think a new package definition should be better, I can look how... The advices I give for people asking me seems to work, but I think a lot of Windows beginners just stop before asking. I put on my groups, but users have already the habit to make with as the windows version has to use curl or wget and that was already a problem with chocolatey.

I hope I've given information enough ;)

**Comment by hyPiRion** [comment] 2015-02-24 23:01
ooh, right. Although stable refers to the correct version (we fixed it on stable), `lein upgrade 2.5.1` will actually download the wrong one because it downloads from the tag name, not stable. `lein upgrade` will actually download the correct one, so I guess I'll just alert people to do that.

For new users, they should download from [lein.bat from the stable branch](https://github.com/technomancy/leiningen/blob/stable/bin/lein.bat) – which should be working as intended.

I'll see if I can cook up a fix here, but it isn't as easy as to just move the tag itself unfortunately.

**Comment by ivanpierre** [comment] 2015-02-24 23:10
I know ;) Perhaps a temporary gist or somewhat...

**Comment by ivanpierre** [comment] 2015-02-24 23:55
OK, I tested. If wget or curl are not installed, program hangs.
We arrive to the #1800 problem with unable to verify issuer's certificate.
So this specific (v2.5.1) problem should work...

**Comment by ivanpierre** [comment] 2015-03-22 14:06
Ok, downloading the last version of lein.bat downloads the 2.5.1-standalone.jar nicely now without certificate error, but it downloads the 2.5.1 version of lein.bat too, so further call to 'lein upgrade' fails.

**Comment by ivanpierre** [comment] 2015-03-22 14:25
Ok, last version of the batch _lein self-install_ with changed version to 2.5.1 works nicely.
But just a warning, a call to _lein upgrade_ will reinstall the old lein.bat of version 2.5.1 if version 2.5.2 is not ready. In case some user complains.... :D

**Comment by hyPiRion** [comment] 2015-03-22 15:52
Yeah, it's not a good situation to be in. I'm working on preparing 2.5.2, hopefully we can get it out in at most 1-2 weeks. That should at least not give people upgrading to latest any problems.

**Comment by ivanpierre** [comment] 2015-03-22 23:41
I just share infos about around.  The windows install should be verified too when the 2.5.2 is out, I think it will not work, as the chocolatey version... Perhaps a git version to be synched could be nice.... as the package and rpm in the linux world that are clearly out of date and distributed around if you try to search on google and in the linux sites.
I know that programmers unable to download a script in their path will perhaps have difficulty creating a project, but perhaps an easy way to install a newbie config can be a first bad step to avoid... just a thought. Working about, in free time...

**Comment by breakingco** [comment] 2015-04-10 07:39
aha! Finally I could download lein (to Windows, no problems on Mac) using that updated bat from the gist. My issue was different to this though - ERROR: cannot verify github.com's certificate, issued by `/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Ex
nded Validation Server CA':.

Been searching for a solution for this for hours, maybe the new bat could also include some note about it fixing this problem also. Thanks!

**Comment by ivanpierre** [comment] 2015-04-10 08:32
Normally, if you take the last version (not the linked one). And change the version number to 1.5.1, it should do the thing. It uses the PowerShell to download the file, so, there's no certificate program. If it tries with curl or wget, you have the certificate problem.
Patch used : https://github.com/technomancy/leiningen/pull/1831

**Comment by hyPiRion** [comment] 2015-08-09 14:02
This should be resolved by the release of 2.5.2.

**Closed by hyPiRion** 2015-08-09 14:02 UTC
Labels: bug, Windows
