### ISSUE TITLE
uberjars don't set multi-release when appropriate

### ISSUE THREAD

**Issue by dpsutton** [technomancy/leiningen#2744] opened 2021-05-11 20:18 UTC
**Describe the bug**
Making an uberjar when one of your dependencies is a multi-release jar does not mark your jar as multi-release

**To Reproduce**
```clojure
(defproject aproject "0.0.1"
  :dependencies     [[org.apache.logging.log4j/log4j-core "2.13.3"]
                     [org.apache.logging.log4j/log4j-api "2.13.3"]])
```

`lein uberjar`

log4j is a multi-release jar which includes code specific to different jvm version. When 

**Actual behavior**
The manifest file does not include `Multi-Release: true`

**Expected behavior**
The manifest file includes this entry to correctly mark the jar as multi-release.

**Workaround**
specify
```clojure
  :manifest {"Multi-Release" true}
```

in project.clj

**Comment by technomancy** [comment] 2021-12-29 18:57
This seems like a duplicate of #2743.

**Closed by technomancy** 2021-12-29 18:57 UTC
