### ISSUE TITLE
"Host name may not be empty" with lein installed via apt on Ubuntu 18.04

### ISSUE THREAD

**Issue by ihavenonickname** [technomancy/leiningen#2428] opened 2018-05-06 03:19 UTC
In the following environment:

```
$ apt --version
apt 1.6.1 (amd64)
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

With a fresh project created by `lein`:

```
$ lein new test-report-bug
Generating a project called test-report-bug based on the 'default' template.
The default template is intended for library projects, not applications.
To see other templates (app, plugin, etc), try `lein help new`.
$ cd test-report-bug/
```

It won't run almost any command:

```
$ lein test
Could not transfer artifact org.clojure:clojure:jar:1.8.0 from/to central (https://repo1.maven.org/maven2/): Host name may not be empty
Could not transfer artifact org.clojure:clojure:jar:1.8.0 from/to clojars (https://repo.clojars.org/): Host name may not be empty
Could not transfer artifact org.clojure:tools.nrepl:jar:0.2.12 from/to central (https://repo1.maven.org/maven2/): Host name may not be empty
Could not transfer artifact org.clojure:tools.nrepl:jar:0.2.12 from/to clojars (https://repo.clojars.org/): Host name may not be empty
Could not transfer artifact clojure-complete:clojure-complete:jar:0.2.4 from/to central (https://repo1.maven.org/maven2/): Host name may not be empty
Could not transfer artifact clojure-complete:clojure-complete:jar:0.2.4 from/to clojars (https://repo.clojars.org/): Host name may not be empty
Could not transfer artifact org.clojure:clojure:pom:1.8.0 from/to central (https://repo1.maven.org/maven2/): Host name may not be empty
Could not transfer artifact org.clojure:tools.nrepl:pom:0.2.12 from/to central (https://repo1.maven.org/maven2/): Host name may not be empty
Could not transfer artifact clojure-complete:clojure-complete:pom:0.2.4 from/to central (https://repo1.maven.org/maven2/): Host name may not be empty
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

Here are some possibly useful infos:

* I'm not behind a proxy
* Running it with `sudo` didn't make any difference

```
$ lein version
Leiningen 2.8.1 on Java 1.8.0_162 OpenJDK 64-Bit Server VM
$ java --version
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
```

**Comment by winks** [comment] 2018-05-06 07:12
I don't have a bionic test VM ready, but I'll see what I can do next week

**Comment by kenrestivo-stem** [comment] 2018-05-07 17:00
https://xkcd.com/979/

**Comment by ihavenonickname** [comment] 2018-05-07 17:40
Always a relevant xkcd.

**Comment by winks** [comment] 2018-05-11 05:29
OK, so something is fishy with the SSL stuff in `openjdk-11-jre` which may be installed by default.
Here's what I did on a fresh install: (ref #2421 )
```
sudo apt-get install openjdk-8-jdk
sudo update-alternatives --config java
./lein repl
# => trustAnchors error
sudo apt-get purge java-common
sudo apt-get install openjdk-8-jdk
./lein repl
# => it works
```

**Comment by ehashman** [comment] 2018-08-21 02:53
@ihavenonickname hi, I'm the Leiningen maintainer in Debian (and by proxy Ubuntu)!

Please file Ubuntu-specific bugs against Ubuntu, otherwise I won't see them... I only happened on this by chance because I need to file my own bug, and I'm two months late :sweat_smile: 

Purging java-common does not seem like an acceptable workaround.

This bug claims to have been fixed on the linked StackOverflow issue in the Ubuntu Java stack on August 7th... I am taking a couple week break off any non-emergency package maintenance while my normal build farm gets its AC repaired so if someone can't check to see if this is fixed in the short term, I'll attempt to reproduce in early September.

**Comment by ehashman** [comment] 2018-08-21 03:06
For the record: relevant upstream bugs affect the entire Java toolchain:

- Ubuntu: https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1739631
- Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894979

These are both closed now, the Ubuntu one having been uploaded into the stable release (bionic) on July 30th, 2018.

**Comment by ihavenonickname** [comment] 2018-08-24 12:05
@ehashman 

> file Ubuntu-specific bugs against Ubuntu

Sorry, I don't understand... Is there a specific issuetracker I should use to open Ubuntu-related bugs?

**Comment by ehashman** [comment] 2018-08-24 12:07
@ihavenonickname yup! Bugs in Ubuntu packages should be filed on Launchpad: https://bugs.launchpad.net/ubuntu/+source/leiningen-clojure

**Closed as completed** 2018-09-20 21:24 UTC
