### ISSUE TITLE
OpenJDK Warning

### ISSUE THREAD

**Issue by lffg** [technomancy/leiningen#2674] opened 2020-04-08 18:20 UTC
When I run `lein` or any of its subcommands, I get the following warning in the first line:

> OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

How can I resolve this issue to get rid of the warning?

I'm using Leiningen 2.9.3 on Java 14 OpenJDK 64-Bit Server VM.

**Comment by technomancy** [comment] 2020-04-08 19:02
This is a duplicate of #2611 

You can `export LEIN_JVM_OPTS="-XX:TieredStopAtLevel=1"` to fix this on your machine but unfortunately there is no way to fix this in Leiningen itself without having disastrous startup time consequences on OpenJDK 8.

**Closed by technomancy** 2020-04-08 19:02 UTC
