### ISSUE TITLE
Respect nrepl dependency for lein pom

### ISSUE THREAD

**Issue by shlevy** [technomancy/leiningen#1929] opened 2015-07-08 12:43 UTC
If a project specifies an nrepl dependency (e.g. `[org.clojure/tools.nrepl "0.2.10"]`), `lein pom` ignores it and instead unconditionally generates a `test`-scoped dependency on `nrepl` version `0.2.6`.

**Comment by hyPiRion** [comment] 2015-07-25 16:11
This is a duplicate of #1748.

**Closed by hyPiRion** 2015-07-25 16:11 UTC
