### ISSUE TITLE
lein 2.5.1 adds empty Main-Class property to manifest when using ':main nil'

### ISSUE THREAD

**Issue by ipostelnik** [technomancy/leiningen#1850] opened 2015-03-05 17:20 UTC
If you specify `:main nil` in project.clj, you get empty `Main-Class:` entry in the manifest. Previous version completely omited `Main-Class` line. This causes problems for creating jars with multiple main entry points, for instance for use in hadoop.

**Comment by hyPiRion** [comment] 2015-03-05 17:50
Duplicate of #1814, which is solved on master.

**Closed by hyPiRion** 2015-03-05 17:50 UTC
