### ISSUE TITLE
Provided scope is not propagated on composite profiles

### ISSUE THREAD

**Issue by bbatsov** [technomancy/leiningen#2687] opened 2020-06-07 08:45 UTC
Recently I've tracked down a [bizarre issue](https://github.com/clojure-emacs/orchard/issues/91) with Orchard 0.5.9 to Lein 2.9.3 not honouring the Clojure exclusions there and adding Clojure from the provided profile (1.10) as a runtime dep (more details can be found in the issue conversation - https://github.com/clojure-emacs/orchard/issues/91).

Here's the `project.clj` in question:

```clj
(defproject cider/orchard "0.5.10"
  :description "A fertile ground for Clojure tooling"
  :url "https://github.com/clojure-emacs/orchard"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :scm {:name "git" :url "https://github.com/clojure-emacs/orchard"}

  :dependencies [[org.tcrawley/dynapath "1.1.0"]
                 [org.clojure/clojurescript "1.10.520"]]
  :exclusions [org.clojure/clojure] ; see versions matrix below

  :aliases {"bump-version" ["change" "version" "leiningen.release/bump-version"]}

  :release-tasks [["vcs" "assert-committed"]
                  ["bump-version" "release"]
                  ["vcs" "commit" "Release %s"]
                  ["vcs" "tag" "v" "--no-sign"]
                  ["bump-version"]
                  ["vcs" "commit" "Begin %s"]]

  :deploy-repositories [["clojars" {:url "https://clojars.org/repo"
                                    :username :env/clojars_username
                                    :password :env/clojars_password
                                    :sign-releases false}]]

  :profiles {
             ;; Clojure versions matrix
             :provided [:1.10]
             :1.8 {:dependencies [[org.clojure/clojure "1.8.0"]
                                  [org.clojure/clojure "1.8.0" :classifier "sources"]]}
             :1.9 {:dependencies [[org.clojure/clojure "1.9.0"]
                                  [org.clojure/clojure "1.9.0" :classifier "sources"]]}
             :1.10 {:dependencies [[org.clojure/clojure "1.10.1"]
                                   [org.clojure/clojure "1.10.1" :classifier "sources"]]}
             :master {:repositories [["snapshots"
                                      "https://oss.sonatype.org/content/repositories/snapshots"]]
                      :dependencies [[org.clojure/clojure "1.11.0-master-SNAPSHOT"]
                                     [org.clojure/clojure "1.11.0-master-SNAPSHOT" :classifier "sources"]]}

             :test {:resource-paths ["test-resources"]}

             ;; Development tools
             :dev {:dependencies [[pjstadig/humane-test-output "0.10.0"]]
                   :resource-paths ["test-resources"]
                   :plugins [[com.jakemccrary/lein-test-refresh "0.23.0"]]
                   :injections [(require 'pjstadig.humane-test-output)
                                (pjstadig.humane-test-output/activate!)]
                   :test-refresh {:changes-only true}}

             ;; CI tools
             :cloverage {:plugins [[lein-cloverage "1.1.2"]]}

             :cljfmt {:plugins [[lein-cljfmt "0.6.4"]]
                      :cljfmt {:indents {as-> [[:inner 0]]
                                         with-debug-bindings [[:inner 0]]
                                         merge-meta [[:inner 0]]
                                         letfn [[:block 1] [:inner 2]]}}}

             :eastwood {:plugins [[jonase/eastwood "0.3.4"]]
                        :eastwood {:config-files ["eastwood.clj"]}}})

```

`lein deploy` with 2.9.3 resulted in incorrect deps for the library, downgrading Leiningen to 2.9.1 fixed this issue (I haven't tried with 2.9.2 just because 2.9.1 solved my immediate problem). I wasn't able to figure out which of the recent changes resulted in this regression, but I've decided to report it anyways. You can easily compare the different deps generated by Lein 2.9.3 and 2.9.1 [here](https://clojars.org/cider/orchard/versions/0.5.9) and [here](https://clojars.org/cider/orchard/versions/0.5.10). As the issue is relatively subtle I'm guessing some people were bit by it, but they didn't even notice it. 

Anyone can easily reproduce the issue by running `lein install` in Orchard's project dir.

**Comment by glts** [comment] 2020-06-08 13:04
There is a problem here, but it has nothing to do with the top-level
`:exclusions` key. Global `:exclusions` only add an `<exclusions>`
element to all dependencies, it does not cause dependencies from
profiles to somehow be excluded from the Leiningen project map.

I’ve looked at Orchard and I see that the POM files produced by
`lein pom` have begun to diverge between Leiningen 2.9.1 and 2.9.3. The
POM files produced by `lein jar` and included in the JAR are still
identical. You can verify this by looking at the artefacts at
https://repo.clojars.org/cider/orchard/0.5.9, pom.xml inside the JAR is
different from plain pom.xml. I suspect this is another side-effect of
the early profiles merge in #2593, but not yet sure.

**Comment by bbatsov** [comment] 2020-06-08 13:09
> You can verify this by looking at the artefacts at
https://repo.clojars.org/cider/orchard/0.5.9, pom.xml inside the JAR is
different from plain pom.xml

I had noticed this as well, but had no idea where this difference came from. 

> I suspect this is another side-effect of
the early profiles merge in #2593, but not yet sure.

Thanks for looking into this! 🙇‍♂️

**Comment by glts** [comment] 2020-06-08 16:04
It was something else. Unfortunately not an easy one, both 2.9.3/master
and 2.9.1 don’t work as expected. I think the problem is that composite
profiles were never fully implemented.

To illustrate, in the Orchard project, this part of project.clj doesn’t
work properly, both `lein pom` and `lein jar` produce defective POMs,
with the dependencies missing or not having ‘provided’ scope:

    :profiles
    {:provided [:1.10]
     :1.10 {:dependencies [[org.clojure/clojure "1.10.1"]
                           [org.clojure/clojure "1.10.1" :classifier "sources"]]}}

But when expressing the same thing with a non-composite profile, both
`lein pom` and `lein jar` produce the same, correct POM, with the
dependencies having ‘provided’ scope:

    :profiles
    {:provided {:dependencies [[org.clojure/clojure "1.10.1"]
                               [org.clojure/clojure "1.10.1" :classifier "sources"]]}}

I don’t know if anybody noticed or reported this before, but it has been
like this for ever. In Orchard, it’s just that before 2.9.3 the end
result – even though defective – happened to work well.

**Comment by glts** [comment] 2020-06-08 20:06
Work-around:

    :profiles
    {:provided [:1.10]
     :1.10 ^{:pom-scope :provided} {:dependencies [[org.clojure/clojure "1.10.1"]
                                                   [org.clojure/clojure "1.10.1" :classifier "sources"]]}}

**Comment by technomancy** [comment] 2020-07-08 00:43
This is a problem inherent in how we propagate metadata about profiles; we normally use metadata to attach the pom scope to all dependencies inside the `:provided` profile. However, when the profile consists of a keyword, we can't do this, because in Clojure, keywords are not allowed to have metadata attached to them.

I don't think we can fix this without a serious rewrite of how profiles are handled, unfortunately. Best to use the workaround above.

**Comment by bbatsov** [comment] 2020-07-08 05:17
Fair enough. Might be a good idea to document the problem and the workaround somewhere in the profiles documentation.

**Comment by technomancy** [comment] 2020-07-08 19:15
Maybe it would be better if we just flagged this as an error if we detected that the provided profile was composite? Is there any point to using the provided profile if it doesn't propagate `scope=provided` to its dependencies?

**Comment by bbatsov** [comment] 2020-07-09 04:54
> Maybe it would be better if we just flagged this as an error if we detected that the provided profile was composite?

Great idea!

Is there any point to using the provided profile if it doesn't propagate scope=provided to its dependencies?

None.

**Comment by technomancy** [comment] 2020-07-09 16:25
Cool; it's not ideal but it's better than failing to propagate silently. It's mentioned in the profile guide now in 8fb39db. Since there's not much more to be done here I'll close this on out.

**Closed by technomancy** 2020-07-09 16:25 UTC
Labels: bug

**Comment by bbatsov** [comment] 2020-07-09 16:32
Thanks! :bowing_man:

**Comment by technomancy** [comment] 2023-02-04 19:24
Related: this is the same root cause cropping up elsewhere: https://codeberg.org/leiningen/leiningen/issues/14
