### ISSUE TITLE
Blocking if user namespace derefs a future

### ISSUE THREAD

**Issue by martinklepsch** [technomancy/leiningen#2122] opened 2016-04-01 18:40 UTC
If a `user.clj` is present and it or any of it's required namespaces contain a line like `(deref (future (...))` launching a REPL will block until it eventually times out.

There's a minimal repro here: https://github.com/martinklepsch/user-future-deref-block

**Comment by hyPiRion** [comment] 2016-04-01 18:46
Huh, that's interesting – and very weird. Thanks for the report.

**Comment by sgdread** [comment] 2016-08-05 23:57
Just hit this problem with luminus template (file is in ../env/dev/clj/user.clj. Haven't touched the file since the project generation, at one point repl stopped working.
Once commented out all the content in user ns, the problem disappeared. 
Thanks @martinklepsch, this report saved me tons of time. 
Not sure if problem with leinigen since figwheel is also affected. I wonder if this might be reincarnation of 2008 defect: https://groups.google.com/forum/#!topic/clojure/L2wmF7S67zQ

**Comment by glts** [comment] 2019-05-15 11:15
This is (now was) a Clojure bug. It is reproducible in Clojure 1.10.0, but fixed in Clojure 1.10.1-beta1 and later.

**Comment by technomancy** [comment] 2022-04-06 21:55
Thanks!

**Closed by technomancy** 2022-04-06 21:55 UTC
Labels: bug
