### ISSUE TITLE
lein run messes with shutdown hooks

### ISSUE THREAD

**Issue by amalloy** [technomancy/leiningen#1854] opened 2015-03-12 21:10 UTC
I'm not sure if this is expected behavior or what, but lein did something surprising when there were JVM shutdown hooks present. When running my project via `lein run -m whatever`, ctrl-c seems to forcibly kill the process, without waiting for shutdown hooks to finish; `lein trampoline run -m whatever` doesn't have this behavior, instead allowing all shutdown hooks to run to completion.

I tried adding `:eval-in :trampoline` to my project, since a reading of leiningen.core.eval suggests that is a thing I might be able to do, but this just makes `lein run -m whatever` exit immediately without running my code at all, so I gather that is not something I'm supposed to do.

**Comment by hyPiRion** [comment] 2015-03-13 14:55
Yeah, that happens because we forcibly kill subprocesses:

https://github.com/technomancy/leiningen/blob/14379a7305cb9d99eab9f63fba0ee8769b90280c/leiningen-core/src/leiningen/core/eval.clj#L168-L169 – seems reasonable to do something else than `.destroy()` if it's possible.

Happy to take a patch which handles this.

**Comment by jhalterman** [comment] 2015-10-21 00:47
FWIW, this applies to `lein test` as well.

**Comment by evanostroski** [comment] 2015-11-06 04:55
Ok, so I'm a bit of a newbie, not just to this project, but to FOSS period. Are you wanting me to modify this pull to handle this other bug as well?

**Comment by hyPiRion** [comment] 2015-11-06 06:59
@evanostroski: Oh, sorry – I don't usually leave comments while I'm in the process of reviewing a pull request. I should probably reconsider that.

**Comment by evanostroski** [comment] 2015-11-06 13:17
@hyPiRion No worries, I was just getting curious!

**Comment by hyPiRion** [comment] 2015-11-21 20:08
I tried to repeat this issue, but it seems like this is Windows/cygwin-specific. Sending a sigterm or sigint to a java process on OS X/Linux seems to propagate that term/int message downstream. Which seems to make sense, given that Ctrl-D and Ctrl-C works as expected in a repl on those systems.

**Comment by evanostroski** [comment] 2015-11-22 16:40
Okay, I can install cygwin and run some tests. I'm guessing the print3 app you wrote would be a good start?

**Comment by jhalterman** [comment] 2015-11-22 17:31
I was actually hitting this on OSX - my shutdown hook was never called when doing ctrl-c.

**Comment by hyPiRion** [comment] 2015-11-23 19:23
Ugh, this is slightly more bothersome than I initially thought (hence the removal of Newbie).

It seems like this is a problem that isn't solved yet. [Eclipse JDT](https://bugs.eclipse.org/bugs/show_bug.cgi?id=38016), for instance, seem to put it as won't fix because the JVM cannot provide these guarantees.

We probably should have a reproducible example here though, for completeness.

**Comment by hyPiRion** [comment] 2016-01-18 17:08
Closing as the JVM can't provide the requirements to solve this one.

**Closed by hyPiRion** 2016-01-18 17:08 UTC
Labels: bug

**Comment by aphyr** [comment] 2018-03-31 09:06
Just gonna register that this is frustrating me too--would you be open to a patch using, say, `Runtime.exec` to shell out to `kill` on *nix platforms, before falling back to `.destroy`?

**Comment by technomancy** [comment] 2018-03-31 18:25
@aphyr yeah, if `kill` is safer I'd take a patch to do that on platforms where it's supported, though including a flag to revert to the old behavior would be nice just in case there are unforeseen consequences.
