### ISSUE TITLE
IOException - REPL crashing while typing

### ISSUE THREAD

**Issue by ghost** [technomancy/leiningen#2533] opened 2019-02-14 22:49 UTC
I'm coding in Clojure and have been using Lein's REPL thoroughly. But recently it's been crashing all the time while I'm typing, especially while opening or closing maps or parenthesis, with the following error message:

        IOException Recurso temporariamente indisponível
        java.io.FileInputStream.readBytes (FileInputStream.java:-2)
        java.io.FileInputStream.read (FileInputStream.java:255)
        java.io.BufferedInputStream.fill (BufferedInputStream.java:246)
        java.io.BufferedInputStream.read (BufferedInputStream.java:265)
        jline.internal.NonBlockingInputStream.run (NonBlockingInputStream.java:294)
        java.lang.Thread.run (Thread.java:748)
    Bye for now!
"Recurso temporariamente indisponível" means "Resource temporarily unavailable" in English. This message is dumped right at stdout, no line feed is printed. Also, notice that the stack trace points to the line "-2" at FileInputStream.java, which is really weird. I haven't found a single comment about an error like this online.

I'm using Leiningen v2.7.1 from SDKMAN package manager. I was using 2.8.1 and 2.9.0 before, directly taken from leiningen.org, but changing versions didn't help. I'm using Java 8.0.202-amzn from SDKMAN too.

**Comment by danielcompton** [comment] 2019-02-14 23:31
Hi @ydorea 

A few initial debugging questions:

* What do you have in your `~/.lein/profiles.clj`? 
* What dependencies do you have in the project, or is this just a bare `lein repl` without a project.clj? 
* Does this error still occur if you move your profiles.clj out of the way?

It sounds like this error may be coming from third-party plugins/dependencies?

**Comment by ydorea** [comment] 2019-02-15 02:22
Well, you got it in a glance! I had this on my profiles.clj:
`{:repl {:plugins [[cider/cider-nrepl "0.19.0"]]
        :dependencies [[nrepl "0.5.3"]]}}`
It must've been me following some tutorial some days ago...
Thank you very much!

**Comment by narkisr** [comment] 2019-02-16 12:36
Im getting this for my project 

https://github.com/re-ops/re-core/blob/master/project.clj

I can see other reports regarding this:

https://superuser.com/questions/1405886/ioexception-leiningen-repl-crashing-while-typing

[re-core]λ: IOException Resource temporarily unavailable
	java.io.FileInputStream.readBytes (FileInputStream.java:-2)
	java.io.FileInputStream.read (FileInputStream.java:255)
	java.io.BufferedInputStream.fill (BufferedInputStream.java:246)
	java.io.BufferedInputStream.read (BufferedInputStream.java:265)
	jline.internal.NonBlockingInputStream.read (NonBlockingInputStream.java:166)
	jline.internal.NonBlockingInputStream.read (NonBlockingInputStream.java:135)
	jline.internal.NonBlockingInputStream.read (NonBlockingInputStream.java:243)
	jline.internal.InputStreamReader.read (InputStreamReader.java:257)
	jline.internal.InputStreamReader.read (InputStreamReader.java:194)
	jline.console.ConsoleReader.readCharacter (ConsoleReader.java:2151)
	jline.console.ConsoleReader.readCharacter (ConsoleReader.java:2141)
	jline.console.ConsoleReader.readBinding (ConsoleReader.java:2226)

**Comment by ydorea** [comment] 2019-02-16 13:35
That's actually my own report too, I posted here and there.

Also, this morning I experienced it again, I just thought that deleting the profiles.clj resolved the issue, but it didn't...

**Comment by narkisr** [comment] 2019-02-16 13:45
It seems to be random (maybe threading related?) I can see it more on some systems then others and when I launch futures

**Comment by ydorea** [comment] 2019-02-16 13:50
At superuser community, someone noted that they just released Lein 2.9.0 on SDKMAN. I downloaded it and it's working fine, but I'll keep using for a day or two before closing this issue.

**Comment by narkisr** [comment] 2019-02-16 13:50
Iv tried both 2.8.3 and 2.9.0 and it didn't seem to make any difference

**Comment by PrasannaVenkadesh** [comment] 2019-02-16 13:57
Facing same issue. Here is my `lein --version` output

    Leiningen 2.8.1 on Java 1.8.0_191 OpenJDK 64-Bit Server VM

Running on Ubuntu 18.04 x86_64. I don't have the file `~/.lein/profiles.clj`

**Comment by technomancy** [comment] 2019-02-16 17:00
I see. Well, if you can provide any hints on how to reproduce it on another machine that would be great; thanks.

**Comment by PrasannaVenkadesh** [comment] 2019-02-16 17:49
I didn't have `~/.lein/profiles.clj` while getting this error. I noticed that my leiningen (version 2.8.1 on Ubuntu 18.04) was shipped with `nrepl-0.2.12`. 

I created `profiles.clj` and added `[nrepl/lein-repl "0.3.2"]` for `:user` and haven't receive this error yet.

**Comment by danielcompton** [comment] 2019-02-17 00:30
Are there any other plugins in your project.clj?

**Comment by ydorea** [comment] 2019-02-17 00:42
It's not an issue with a specific project. It was happening anywhere I executed the REPL. But today it didn't happen... I hope SDKMAN's update fixed it.

**Comment by tuddman** [comment] 2019-02-21 22:02
also starting experiencing this, too, lately.  Across projects with varying dependencies...

```
Leiningen 2.8.1 on Java 1.8.0_191 OpenJDK 64-Bit Server VM
```
on Ubuntu 18.04

Seems to happen more when copy/pasting in unbalanced? forms.  Sorry, I haven't been able to isolate who/what is the culprit, or create a repo where it _doesn't_ happen.

**Comment by ydorea** [comment] 2019-02-22 00:16
Yeah, this is very erratic for me too. And it's still happening. My workflow became basically typing in a text editor and pasting it at REPL. This way it doesn't break, it only breaks when I'm typing something. But it's annoying.

**Comment by danielcompton** [comment] 2019-02-22 01:25
If you're having issues here, please provide a minimal reproducible case, specifying the dependencies and plugins that you have in both your `~/.lein/profiles.clj`, as well as your `project.clj`. Also, please include your Lein version, Java version, OS, and how you installed Leiningen. It seems likely to me that there are some dependency conflicts here, but I don't think we have enough info to reproduce it yet.

**Comment by technomancy** [comment] 2019-02-22 01:46
Other possibly-relevant pieces of data would be the locale and terminal emulator in use.

**Comment by narkisr** [comment] 2019-02-22 03:21
```bash
locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Im using ZSH on Ubuntu 18.04

**Comment by narkisr** [comment] 2019-02-22 08:36
```bash
$ locale

LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

I'm using zsh on Ubuntu 18.04, I don't think this is specific to a Lein version, I'm able to reproduce this in versions 2.7.x 2.8.x and 2.9.x, iv tried both OpenJDK and Oracle JDK, The only thing I didn't try is another Ubuntu version.

The closest mentioning of this bug that I was able to find was in https://github.com/lihaoyi/Ammonite/issues/180 which does mention Ubuntu and JLine

**Comment by narkisr** [comment] 2019-02-22 11:36
Ok, my re-producable case seems to have been related to my use of 'bash -c' in one section of the code

Moving to sh -c seems to have resolved that, I will keep on tracking if this is a still happening in other code paths

**Comment by ydorea** [comment] 2019-02-22 11:44
```
$ locale
LANG=pt_BR.UTF-8
LANGUAGE=pt_BR:pt:en
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=
```

I've experienced this issue, using Leiningen 2.7.x, 2.8.x and 2.9.x... My OS is Ubuntu 16.04, Java 8.0.202-amzn (SDKMAN). It happened in multiple projects (and at ~ too), with and without ~/.lein/profiles.clj. I really can't find a reproducibility pattern apart from the "being when I'm opening/closing parenthesis/maps" thing.

**Comment by tuddman** [comment] 2019-02-22 13:40
has anyone experienced this issue on an OS _other than_ Ubuntu?

**Comment by technomancy** [comment] 2019-02-22 17:03
Is this happening only in a specific terminal emulator?

**Comment by narkisr** [comment] 2019-02-24 13:11
I think that we are all using Ubuntu 18.04, as for the terminal emulator I'm using ZSH on gnome-terminal or Xfce-termain either of which reproduce this issue from time to time

**Comment by technomancy** [comment] 2019-02-24 18:15
If it's only happening on Ubuntu 18.04 maybe it should be tracked on Launchpad; the folks there probably have a better grasp of what changed in that particular release.

**Comment by technomancy** [comment] 2019-02-24 22:01
@trptcolin have you heard of any issues like this that might be affecting jline?

**Comment by trptcolin** [comment] 2019-02-24 23:49
@technomancy - no, first I’ve heard. It *has* to be an issue w/ jline2 though. I have a suspicion around the open/close matching parens being present and NonBlockingInputStream being in the stack trace - there’s apparently another thread involved there so probably a race condition?

**Comment by eggsyntax** [comment] 2019-02-27 15:02
Same here, also Ubuntu 18.04 and gnome-terminal. Only started happening recently, so it may come down to something in a recent Ubuntu update. I've seen it on a couple of projects, but currently [google-civic-clojure](https://github.com/democracyworks/google-civic-clojure).

```
> lein version
Leiningen 2.8.3 on Java 10.0.2 OpenJDK 64-Bit Server VM

> locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

> java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```
Project dependencies:
```
[[org.clojure/clojure "1.7.0"]
 [clj-http "3.3.0"]
 [clj-http-fake "1.0.2"]
 [cheshire "5.6.3"]
 [robert/bruce "0.8.0"]]
```
IIRC I installed lein via the instructions on https://leiningen.org/.
I've got `~/.lein/profiles.clj` moved out of the way, so no impact there.

I've got lein 2.8.1 also on my system; haven't seen it yet on that, but I haven't tried it much; I'll keep an eye out. I also haven't seen it in a CIDER lein repl, which is what I typically use.

Not a big deal for me, just thought another data point might be of use.

**Comment by martin-roos-1981** [comment] 2019-03-01 15:12
Experiencing the same on ubuntu 18.04 , has started recently, has nothing to do with plugins or project i think. (This also happens without any kind of project file at all). 

Showing the user experience below, after i typed the parenthesises for a few times on a line it just goes. Visually it seems to be related to the visual effect of cursor blinking for a short moment on the start of the matching parenthesis.

```
martinr@martinr-ThinkPad-T540p:/tmp/blank$ ls
martinr@martinr-ThinkPad-T540p:/tmp/blank$ ls -la ~/.lein/
total 36
drwxrwxr-x   3 martinr martinr  4096 veebr 28 15:53 .
drwxr-xr-x 100 martinr martinr 12288 märts  1 14:56 ..
-rw-rw-r--   1 martinr martinr 16262 veebr 28 15:50 repl-history
drwxrwxr-x   2 martinr martinr  4096 nov    2  2017 self-installs
martinr@martinr-ThinkPad-T540p:/tmp/blank$ lein new app crash-demo
Generating a project called crash-demo based on the 'app' template.
martinr@martinr-ThinkPad-T540p:/tmp/blank$ cd crash-demo/
martinr@martinr-ThinkPad-T540p:/tmp/blank/crash-demo$ cat project.clj 
(defproject crash-demo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]]
  :main ^:skip-aot crash-demo.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
martinr@martinr-ThinkPad-T540p:/tmp/blank/crash-demo$ lein repl
nREPL server started on port 34461 on host 127.0.0.1 - nrepl://127.0.0.1:34461
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 11.0.1+13
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

crash-demo.core=> (println "yep")
yep
nil
crash-demo.core=> ()()()()IOException Resource temporarily unavailable
	java.io.FileInputStream.readBytes (FileInputStream.java:-2)
	java.io.FileInputStream.read (FileInputStream.java:279)
	java.io.BufferedInputStream.fill (BufferedInputStream.java:252)
	java.io.BufferedInputStream.read (BufferedInputStream.java:271)
	jline.internal.NonBlockingInputStream.run (NonBlockingInputStream.java:294)
	java.lang.Thread.run (Thread.java:834)
Bye for now!
(martinr@martinr-ThinkPad-T540p:/tmp/blank/crash-demo$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
martinr@martinr-ThinkPad-T540p:/tmp/blank/crash-demo$ lein --version
Leiningen 2.8.1 on Java 11.0.1 OpenJDK 64-Bit Server VM
```

**Comment by martin-roos-1981** [comment] 2019-03-01 15:21
I suspected it may be related to env somehow, but seems to happen in xterm, gnome-terminal and even inside of screen and also outside any X server just on the console command line (and also happens when ssh-ing into the localhost and running lein repl there).

**Comment by technomancy** [comment] 2019-03-01 17:23
If this happens only when you're typing parens, it's got to be related to the paren matching functionality of jline.

@trptcolin I went looking for a way to disable this in reply from project.clj but couldn't find it; is there a way to do this that I missed?

**Comment by trptcolin** [comment] 2019-03-01 21:01
@technomancy Agreed. It's not exposed to config currently, but yeah it probably should be. I dropped issues into reply & jline2 for this, and I have instructions on [the reply ticket](https://github.com/trptcolin/reply/issues/197#issuecomment-468810037) that folks can try to verify whether disabling it works.

**Comment by tomprice719** [comment] 2019-03-04 04:09
I get it sporadically when typing closing parens, never noticed it with opening parens. This is with no project file, no leiningen profile, using Ubuntu 18.04.2 LTS, Leiningen installed with apt, gnome terminal, this lein -version output:
Leiningen 2.8.1 on Java 1.8.0_191 OpenJDK 64-Bit Server VM
And this locale:
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=

**Comment by martin-roos-1981** [comment] 2019-03-04 07:31
Noticed that the same thing does not happen on my home box and it was running leiningen 2.9.1 over there. Upgraded leiningen from 2.8.1 to 2.9.1 on crashing machine (the one described above) and i haven't managed to reproduce anymore.

Can anyone at all reproduce this on leiningen 2.9.1 ?

**Comment by bjaglin** [comment] 2019-03-06 21:03
Most likely a kernel issue, see https://github.com/sbt/sbt/issues/4547

**Comment by trptcolin** [comment] 2019-03-06 23:14
Thanks a bunch, @bjaglin! 

For folks looking for a workaround - update your kernels? e.g. `apt install linux-image-4.15.0-46-generic`. I'd expect anyone affected is on one of `4.15.0-44` or `4.15.0-45` (check `uname -a`). I was unaffected on `4.18.0-15`, for what it's worth.

This is pretty wild stuff, definitely didn't expect "kernel bug" to be the outcome here. Maybe I'll see if I can put a blog post or talk or something together, totally nuts.

Here are some relevant discussions:
- LKML: https://marc.info/?t=154883032500001&r=1&w=2
- Ubuntu: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1813873

**Comment by 2formaggi** [comment] 2019-03-20 14:16
@trptcolin after updating the kernel, the repl error just stopped, thanks.

**Comment by winks** [comment] 2019-03-20 16:50
This is such a huge WTF, maybe we should mention the bad kernel ranges in the release notes?

**Comment by technomancy** [comment] 2019-03-20 17:33
> This is such a huge WTF, maybe we should mention the bad kernel ranges in the release notes?

Good call. Do we have a definitive answer on the range?

**Comment by trptcolin** [comment] 2019-03-20 21:57
AFAICT only Ubuntu `4.15.0-44` and `4.15.0-45` are affected.

**Comment by trptcolin** [comment] 2019-03-20 21:58
Whoops, didn’t mean to close, sorry.

**Closed** 2022-04-07 00:41 UTC
Labels: bug, upstream
