### ISSUE TITLE
IncompatibleClassChangeError with 2.8.0 on tmux

### ISSUE THREAD

**Issue by saidone75** [technomancy/leiningen#2326] opened 2017-10-18 20:19 UTC
When launching e.g. a repl inside tmux I got this
```
$ lein repl
nREPL server started on port 33231 on host 127.0.0.1 - nrepl://127.0.0.1:33231
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

IncompatibleClassChangeError Found class jline.Terminal, but interface was expected
        jline.console.ConsoleReader.<init> (ConsoleReader.java:230)
        jline.console.ConsoleReader.<init> (ConsoleReader.java:221)
        jline.console.ConsoleReader.<init> (ConsoleReader.java:213)
        reply.reader.simple-jline/setup-console-reader (simple_jline.clj:71)
        reply.reader.simple-jline/setup-console-reader (simple_jline.clj:71)
        reply.reader.simple-jline/get-input-line (simple_jline.clj:109)
        reply.reader.simple-jline/get-input-line (simple_jline.clj:101)
        clojure.lang.Atom.swap (Atom.java:37)
        clojure.core/swap! (core.clj:2260)
        clojure.core/swap! (core.clj:2253)
        reply.reader.simple-jline/safe-read-line (simple_jline.clj:148)
        reply.reader.simple-jline/safe-read-line (simple_jline.clj:134)
Bye for now!
````
while 2.7.1 is working fine.
```
$ sudo apt show tmux
Package: tmux
Version: 2.1-3build1
```

**Comment by technomancy** [comment] 2017-10-18 23:59
What is the value of the `$TERM` env var when you hit this problem?

**Comment by saidone75** [comment] 2017-10-19 06:21
`screen`

**Comment by winks** [comment] 2017-10-19 14:57
Cannot reproduce on CentOS 7.4 with tmux-1.8, TERM=screen
Cannot reproduce on Debian jessie with tmux 1.9, TERM=xterm-256color
Cannot reproduce on Debian stretch with tmux 2.3,  TERM=xterm-256color

Trying to build that tmux version linked above now

**Comment by winks** [comment] 2017-10-19 15:03
Nevermind, just tried it
Cannot reproduce on Debian stretch with tmux 2.1 (from git), TERM=xterm-256color | TERM=screen

I think there should've been a reference to #2328 if it's the same upstream bug.

**Comment by saidone75** [comment] 2017-10-19 17:46
I was able to track the problem, it's not about tmux but lein-koan/koan-engine:
```
$ lein version
Leiningen 2.7.1 on Java 1.8.0_131 OpenJDK 64-Bit Server VM
$ git clone git://github.com/functional-koans/clojure-koans.git
Cloning into 'clojure-koans'...
remote: Counting objects: 1590, done.
remote: Total 1590 (delta 1), reused 1 (delta 1), pack-reused 1588
Receiving objects: 100% (1590/1590), 267.54 KiB | 90.00 KiB/s, done.
Resolving deltas: 100% (759/759), done.
Checking connectivity... done.
$ cd clojure-koans/
$ lein repl
nREPL server started on port 36503 on host 127.0.0.1 - nrepl://127.0.0.1:36503
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

koan-engine.runner=> Bye for now!
$ lein upgrade
The script at /home/saidone/bin/lein will be upgraded to the latest stable version.
Do you want to continue [Y/n]? y

Upgrading...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   137  100   137    0     0     95      0  0:00:01  0:00:01 --:--:--    95
100 12557  100 12557    0     0   5752      0  0:00:02  0:00:02 --:--:--  215k
WARNING: You have $CLASSPATH set, probably by accident.
It is strongly recommended to unset this before proceeding.
Leiningen 2.8.0 on Java 1.8.0_131 OpenJDK 64-Bit Server VM
$ lein version
Leiningen 2.8.0 on Java 1.8.0_131 OpenJDK 64-Bit Server VM
$ lein repl
nREPL server started on port 44905 on host 127.0.0.1 - nrepl://127.0.0.1:44905
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

IncompatibleClassChangeError Found class jline.Terminal, but interface was expected
	jline.console.ConsoleReader.<init> (ConsoleReader.java:230)
	jline.console.ConsoleReader.<init> (ConsoleReader.java:221)
	jline.console.ConsoleReader.<init> (ConsoleReader.java:213)
	reply.reader.simple-jline/setup-console-reader (simple_jline.clj:71)
	reply.reader.simple-jline/setup-console-reader (simple_jline.clj:71)
	reply.reader.simple-jline/get-input-line (simple_jline.clj:109)
	reply.reader.simple-jline/get-input-line (simple_jline.clj:101)
	clojure.lang.Atom.swap (Atom.java:37)
	clojure.core/swap! (core.clj:2260)
	clojure.core/swap! (core.clj:2253)
	reply.reader.simple-jline/safe-read-line (simple_jline.clj:148)
	reply.reader.simple-jline/safe-read-line (simple_jline.clj:134)
Bye for now!
```
Sorry for having been misleading, hope this will help. Thanks!

**Comment by winks** [comment] 2017-10-24 15:38
both `2.7.1` and `2.8.0` show
`REPL-y 0.3.7, nREPL 0.2.12`
so there nothing should've changed.

I'm kind of clueless where this error comes from.

But googling for the "Found class jline.Terminal, but interface was expected" error, it seems like it has to do with a jline dep bump from `0.9.94` (what `koan-engine` uses) and `2.12.1` (what `reply` uses)

**Comment by trptcolin** [comment] 2017-10-24 16:29
I wasn't able to reproduce this exact error message, but by using `lein trampoline repl` I got a related one where class expectations were mismatched. Upgraded the koan stuff to not use that old jline; it didn't need it. The latest clojure-koans does work fine locally for me - hopefully also for others?

**Comment by winks** [comment] 2017-10-24 16:33
Closing this as upstream fixed this for us (and super quick as well).

Thanks, upstream!

**Closed by winks** 2017-10-24 16:33 UTC
Labels: upstream

**Comment by winks** [comment] 2017-10-24 16:39
Addendum: I could reproduce it verbatim and can't anymore after the last 2 commits in `clojure-koans`
