### ISSUE TITLE
Noob here . An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by mintyPT** [technomancy/leiningen#2341] opened 2017-10-25 22:05 UTC
So, I wanted to learn clojure. Installed leiningen with brew. I generated a project, but when I run it, I always get 

```
lein run -m clojure-noob                                                                               ⏎ master ✭ ✱ ◼
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by dynapath.defaults$eval380$fn__381 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of dynapath.defaults$eval380$fn__381
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
No :main namespace specified in project.clj.
```

Any tips? I searched a bit and found no proper solution. I come from the nodejs world and never touched java so this doesn't make things easy. Any help is very very welcome because I have no idea what to do, and if I can't solve I'll probably drop clojure for another funcional language. Thanks!

**Comment by technomancy** [comment] 2017-10-25 22:16
You can ignore the `WARNING` part; the fix for that is on master and will be released in a stable version in a couple days.

As for the last line; I can't reproduce it. Can you specify which version of Leiningen you are using?

**Comment by danielcompton** [comment] 2017-10-26 01:07
This relates to https://github.com/cemerick/pomegranate/pull/92 I think?

**Comment by technomancy** [comment] 2017-10-26 01:38
The warning does, but the last line is a different problem. It should never look in :main when there is a -m argument given.

**Comment by mintyPT** [comment] 2017-10-26 05:22
Ok. I'll ignore the warning. Regarding the last line, I'm almost ashamed of it :D Being distracted with the warnings I forgot to cd into the projects directory! 

Sorry for your time but thank you very much for your help.

**Comment by technomancy** [comment] 2017-10-26 15:55
No problem; hope the rest of your learning goes smoothly.

**Closed by technomancy** 2017-10-26 15:55 UTC
