### ISSUE TITLE
Unable to create project specific lein task.

### ISSUE THREAD

**Issue by iciclespider** [technomancy/leiningen#2209] opened 2016-09-19 20:02 UTC
In my project.clj file, I am attempting to implement a lein task unique to that project in the project.clj file itself. I almost had this working, but there is a slight bug in the leiningen.core.utils/require-resolve function here: https://github.com/technomancy/leiningen/blob/master/leiningen-core/src/leiningen/core/utils.clj#L92  The implementation of that function is:

    (defn require-resolve
      "Resolve a fully qualified symbol by first requiring its namespace."
      ([sym]
         (if-let [ns (namespace sym)]
           (when (ns-exists? ns)
             (let [ns (symbol ns)]
               (when-not (find-ns ns)
                 (require ns)))
             (resolve sym))
           (resolve sym)))
      ([ns sym] (require-resolve (symbol ns sym))))

The problem is the "(resolve sym)" on the second to last line. This line never gets executed ever. It is inside the (if-let ...) which acts both like an (if ...) and like a (let ...). In this case, the (let ...) is allowing multiple functions to be included, however the (if ...) part skips everything if the (if ...) part fails, thus that final "(resolve sym)" will never, ever run.  This is likely actually a bug in (if-let ...), but this code does appear to think that that final "(resolve sym)" will be run at times.

Here is the code placed at the very bottom of my project.clj that is attempting to create the project specific lein task:

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (in-ns 'leiningen.mytask)
    (clojure.core/refer 'clojure.core)

    (defn mytask
      [project]
      (println "Running mytask"))

**Comment by iciclespider** [comment] 2016-09-20 07:57
After further contemplation, I believe the real issue here is in fact the ns-exists? implementation, which insists that the ns exists in a physical file. What is the reason for this test? Why can't the namespace just exist, regardless of where it resides?

**Comment by hyPiRion** [comment] 2016-09-20 10:56
Yeah, this is not a bug in require-resolve itself, but rather the assumption that the namespace must be physically. Not sure why this is the case, it seems like looking it up through `find-ns` inside `ns-exists?` before doing a physical check would be just fine. Happy to take a patch for this.

**Comment by hyPiRion** [comment] 2016-09-21 07:43
Fixed by 716d833.

**Closed by hyPiRion** 2016-09-21 07:43 UTC
Labels: bug
