### ISSUE TITLE
Leiningen 2.8.0 breaks Eastwood

### ISSUE THREAD

**Issue by emlyn** [technomancy/leiningen#2332] opened 2017-10-20 18:20 UTC
Since upgrading Leiningen to version 2.8.0, Eastwood fails with the following error:

```
Exception in thread "main" java.lang.RuntimeException: No reader function for tag object, compiling:(/private/var/folders/gk/ddnj_fdj49bfldn4zz73mj6w0000gn/T/form-init7644865887821960535.clj:1:8263)
	at clojure.lang.Compiler.load(Compiler.java:7386)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No reader function for tag object
	at clojure.lang.LispReader$CtorReader.readTagged(LispReader.java:1245)
	at clojure.lang.LispReader$CtorReader.invoke(LispReader.java:1228)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:684)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:800)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:792)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1150)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:800)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:792)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.Compiler.load(Compiler.java:7374)
	... 14 more
Subprocess failed
```
(also posted to jonase/eastwood#238)

**Comment by jafingerhut** [comment] 2017-10-20 19:23
Duplicate of this issue, I think: https://github.com/technomancy/leiningen/issues/2328

**Comment by technomancy** [comment] 2017-10-20 21:31
Yeah, this is tracked in #2328.

**Closed by technomancy** 2017-10-20 21:31 UTC
