### ISSUE TITLE
`:main nil` no-longer omits `Main-Class` attribute from manifest

### ISSUE THREAD

**Issue by jaley** [technomancy/leiningen#1823] opened 2015-02-06 13:49 UTC
Hey,

Seems that in 2.5.1, setting `:main nil` in the project causes a blank `Main-Class` line to be added to the manifest file, rather than omitting it altogether. This breaks applications that require multiple entry points, like anything Hadoop-based, for example.

Any workaround suggestions? Rolling back to 2.5.0 for now.

Thanks,
James.

**Comment by hyPiRion** [comment] 2015-02-06 17:38
Hi!

This is a duplicate of #1814, which is solved on master. I'd recommend going with 2.5.0, but if you really need some fixes from 2.5.1, you could run master as per [CONTRIBUTING.md](https://github.com/technomancy/leiningen/blob/master/CONTRIBUTING.md) (it will be a tad slower to start up, as it's not uberjared).

**Comment by jaley** [comment] 2015-02-06 17:50
Ah sorry! I did a quick search but didn't see any obviously relevant titles, oops!

No problem, I can stick with 2.5.0 for now.

**Closed** 2015-02-06 17:58 UTC

**Comment by hyPiRion** [comment] 2015-02-06 18:39
No worries, duplicates aren't that big of a problem :)
