### ISSUE TITLE
Build on CircleCI fails with "Pathological dependency tree detected; consider disabling pedantic."

### ISSUE THREAD

**Issue by gixxi** [technomancy/leiningen#2764] opened 2021-09-16 03:20 UTC
*Leiningen Version* 

2.9.7

works with *2.9.6*

*Description*

coincidence with latest change "Warn when pedantic detects a pathological dependency tree."

Is there a way to disable this feature 

[project.clj.txt](https://github.com/technomancy/leiningen/files/7174703/project.clj.txt)

**Comment by gixxi** [comment] 2021-09-16 03:21
happens with the project.clj

`(defproject rocklog-vlic "21.01-SNAPSHOT-20210916-0444"
  :description "Rocklog WMS based on the Very Large Intralogistics Kernel (VLIC) and Lambdaroyal-Memory"
  :url "https://github.com/lambdaroyal/rocklog-vlic"
  :license {:name "Proprietary"
            :url "http://www.planet-rocklog.com"}
  :dependencies [[org.clojure/clojure "1.10.3"]
                 [org.clojure/spec.alpha "0.2.176"]
                 [org.clojure/tools.cli "0.3.3"]
                 [org.clojure/core.async "0.4.490"]
                 [org.clojure/data.priority-map "0.0.7"]
                 [com.ashafa/clutch "0.4.0"
                  :exclusions [clj-http]]
                 [org.clojure/tools.logging "0.3.1"]
                 [org.slf4j/slf4j-log4j12 "1.7.1"]
                 [org.lambdaroyal/clojure-algorithms "0.2-SNAPSHOT"]
                 [org.lambdaroyal/clojure-util "1.0-SNAPSHOT"]
                 [org.clojars.gixxi/lambdaroyal-memory "1.1.5Beta"]
                 [javax.servlet/servlet-api "2.5"]
                 [ring/ring-json "0.5.0-beta1"]
                 ;;lib for caching (IP location etc.)
                 [org.clojure/core.memoize "0.5.6"]
                 ;;getting geolocations
                 [com.oscaro/maximator "0.1.0"]
                 [com.fasterxml.jackson.core/jackson-core "2.4.2"]
                 [com.fasterxml.jackson.core/jackson-databind "2.4.2"]

                 ;;read-in worksheets
                 [org.apache.commons/commons-vfs2 "2.0"]
                 [commons-lang "2.6"]

                 ;;accepting nRepl Connections
                 [org.clojure/tools.nrepl "0.2.12"]

                 ;;cerberrus
                 [schejulure "1.0.1"]
                 [com.draines/postal "1.11.3"]

                 ;;bugfix for
                 [clj-http "2.0.0"]

                 ;;sankey, rendered on server
                 [com.keminglabs/c2 "0.1.0"]

                 ;;excel export
                 [org.apache.poi/poi-ooxml "3.9"]

                 ;;parsing queries
                 [instaparse "1.4.5"]

                 ;;reading csv
                 [org.clojure/data.csv "0.1.3"]
                                        
                 ;accessing odoo default webservice
                 [xmlrpc/xmlrpc-client "3.0"]
                 ;;aspect testing support
                 [robert/hooke "1.3.0"]

                 ;;handling ftp in interfaces
                 [com.velisco/clj-ftp "0.3.9"]
                 
                 ;job dispatching
                 [org.clojars.gixxi/lambdaroyal-dispatch "0.8"]
                 
                 ;;parsing URLs
                 [org.clojure/core.incubator "0.1.4"]
                 [com.cemerick/url "0.1.1"]

                 ;writing xml files through interfaces
                 [org.clojure/data.xml "0.2.0-alpha6"]

                 [clj-time "0.9.0"]
                 [clj-jwt "0.0.13"]
                 [less-awful-ssl "1.0.4"]
                 [http-kit "2.5.3"]
                 [compojure "1.6.1"]

                 [log4j "1.2.17"
                  :exclusions [javax.mail/mail
                               javax.jms/jms
                               com.sun.jdmk/jmxtools
                               com.sun.jmx/jmxri]]
                 [log4j/apache-log4j-extras "1.2.17"]]
  :profiles {:dev {:dependencies [[midje "1.9.9"]]
                   :resource-paths ["resources"]}}
  :java-source-paths ["src-java"]
  :test-paths ["test" "test-java"]
  :pre-tasks ["javac" "compile"]

  :main lambdaroyal.vlic.main
  :aot [lambdaroyal.vlic.main]
  :plugins [[lein-set-version "0.4.1"]
            [lein-midje "3.2.1"]])`

**Comment by technomancy** [comment] 2021-09-16 16:59
The message you are describing is not a failure; it's a warning. It's hard to say what to do here without understanding what actually failed; can you provide more details?

**Comment by technomancy** [comment] 2021-09-29 17:11
The message actually tells you how to disable it; it's by turning off `:pedantic?`.

Anyway if you have a repro case of an actual failure we can take a closer look here but at present there's really nothing to go on here.

**Comment by technomancy** [comment] 2021-11-04 20:45
I'm pretty sure this is a duplicate of #2763 and #2769.

**Closed by technomancy** 2021-11-04 20:45 UTC

**Comment by technomancy** [comment] 2021-11-04 21:02
Also I think it's fixed in ec5aeec; please let me know if you still get this.
