### ISSUE TITLE
Refactor-nrepl in :user dependencies -> no tools.reader 1.0.0-alpha3 ?

### ISSUE THREAD

**Issue by arichiardi** [technomancy/leiningen#2097] opened 2016-02-21 00:32 UTC
This is the weirdest issue ever and most of the "discovery" steps are described in https://github.com/emezeske/lein-cljsbuild/issues/439.

Steps to reproduce:

1. `git clone -b tools-reader-bug https://github.com/Lambda-X/replumb`
2 In your `profiles.clj` add:
```
{:user
 {:dependencies [[refactor-nrepl "2.0.0-SNAPSHOT"]]
```
3. In the project launch `lein cljsbuild once dev`.
4. Open `resources/public/js/compiled/out/cljs/tools/reader.cljs` and go to line 705.
5  I expect it to match [this](https://github.com/clojure/tools.reader/blob/master/src/main/cljs/cljs/tools/reader.cljs#L705). It does not.

Apparently putting `refactor-nrepl` there (I have not tried other versions) wreaks havoc among dependencies, and in particular `tools.reader`, that now is not at the desired version of `1.0.0-alpha3`.

**Comment by danielcompton** [comment] 2016-02-21 08:28
`refactor-nrepl` bundles tools.reader as a [source dependency](https://github.com/clojure-emacs/refactor-nrepl/blob/master/project.clj#L12) and uses [mranderson](https://github.com/benedekfazekas/mranderson) to copy it over into it's own source tree. It also munges the names into a private namespace. Looking at the [POM](https://clojars.org/repo/refactor-nrepl/refactor-nrepl/2.0.0-SNAPSHOT/refactor-nrepl-2.0.0-20160206.122040-20.pom) tools.reader isn't a dependency there. Unzipping the [JAR](https://clojars.org/repo/refactor-nrepl/refactor-nrepl/2.0.0-SNAPSHOT/refactor-nrepl-2.0.0-20160206.122040-20.jar), I can see `<jar root>/mranderson046/toolsreader/v0v10v0_alpha3/clojure/tools/reader.clj`. The Clojure file has been munged into it's own private namespace. However look at `<jar root>/cljs/tools/reader.cljs`. It doesn't look like mranderson is munging ClojureScript files, so they are getting bundled by refactor-nrepl. Again, similar to the Leiningen Uberjar issue, refactor-nrepl is copying all of the dependencies as source dependencies so they won't show up as a classpath conflict.

**Comment by hyPiRion** [comment] 2016-02-21 14:05
Yeah, so I guess this is an issue with mranderson then, and not really with Leiningen itself? With #2094 that would probably be easier to notice, I guess.

**Comment by arichiardi** [comment] 2016-02-21 16:09
Maybe the should be a strategies when duplicate files are found on the classpath that gives precedence to the direct dependences..

**Comment by danielcompton** [comment] 2016-02-21 18:16
It's not possible for Leiningen to know which JAR is a direct dependency and which has uberjarred a bunch of files. The only thing you can do is change your classpath ordering by changing which order your plugins are specified. I'm not sure whether :user profile deps always come ahead of project ones though.

**Comment by hyPiRion** [comment] 2016-02-21 21:25
It would be possible to lower the priority of `:user` profile dependencies, but that would change the priority for other keys, which I'm not too fond of doing without some research on its impact. Besides, it would only solve some symptoms, and not the root cause of this issue.

Does it seem reasonable to send out a warning if we notice duplicates of `.clj/.cljc/.cljs` files? It's too expensive to do it on startup, so it would only be done when uberjaring at the moment.

**Comment by arichiardi** [comment] 2016-02-21 22:22
@hyPiRion The problem is that this was happening on `lein cljsbuild once dev` or `lein doo phantom` so I guess I warning should be thrown in other commands as well.

**Comment by danielcompton** [comment] 2016-02-21 23:16
The issue in this case was that one uberjar (refactor-nrepl) bundled tools.reader, and a user project also specified tools.reader. So the error only occurs when both of those JARs are on the Classpath. The refactor-nrepl people will never get a warning. I think it could be good to add as a `lein deps` command, maybe added to `:tree`. It would scan through all of the namespaces on the classpath, and warn if there were duplicates then. However, I don't even know if this is possible?

**Comment by hyPiRion** [comment] 2016-02-21 23:57
@danielcompton It's not possible to notice duplicate namespaces (turing complete), but we can easily notice duplicate files – this is what we do when we uberjar files. Wouldn't that be sufficient in most cases?

**Comment by danielcompton** [comment] 2016-02-22 00:51
Duplicate file paths might work, but the file content could be different, e.g. tools.reader 0.10.0 in one uberjar, and tools.reader 0.11.0 in user deps. I think that's what you're talking about?

**Comment by arichiardi** [comment] 2016-02-22 05:49
Shouldn't we just exclude :user deps from the build of any uber-kind-of-jar? Maybe it's a bit too extreme but I found (my bad maybe) a bit confusing that bit. I would never have expected that my final artifact would include stuff from there...just a thought

**Comment by benedekfazekas** [comment] 2016-02-27 20:09
this is now fixed in [mranderson](https://github.com/benedekfazekas/mranderson), see benedekfazekas/mranderson#12 see steps to retest in that issue. let me know if the fix is good.

**Comment by benedekfazekas** [comment] 2016-08-30 10:28
just stumbled upon this one. I suppose this is fixed in mranderson, perhaps good for a close?

**Comment by arichiardi** [comment] 2016-08-30 14:42
The problem was solved for me after that fix, yes.

**Closed** 2016-08-30 14:43 UTC
