### ISSUE TITLE
Classpath order is not honored

### ISSUE THREAD

**Issue by rauhs** [technomancy/leiningen#2283] opened 2017-06-11 08:14 UTC
I need to rely on the fact that a dependency `A` comes before dependency `B` on the classpath. Currently by specifying `A` before `B` in the `:dependencies` vector does not necessarily generate a classpath that honors this. It seems that the dependencies are turned into a `set` before the classpath gets generated. Maven on the other hand does generate a classpath in the same order the dependencies are declared.

**Comment by rauhs** [comment] 2017-07-11 10:37
Quick reproduce:
```clojure
(defproject xyz "0.1"
  :dependencies
  [[org.clojure/core.async "0.3.442"]
   [org.clojure/data.json "0.2.6"]])
```

```
$ lein classpath | tr ':' '\n' | ag "async|json"
/home/rauh/.m2/repository/org/clojure/data.json/0.2.6/data.json-0.2.6.jar
/home/rauh/.m2/repository/org/clojure/core.async/0.3.442/core.async-0.3.442.jar
```

**Comment by glts** [comment] 2017-07-31 15:56
I believe this might be a flaw in both Leiningen and Pomegranate.

If it is by design, it is a significant departure from Maven and I
would disagree with it. I have opened cemerick/pomegranate#86.

**Comment by glts** [comment] 2017-08-01 20:53
Here is an example for what I have called a ‘flaw’ above. In a project that declares dependencies on Clojure 1.8 and `[ring "1.6.2"]`, `lein deps :tree` will present the dependency hierarchy in alphabetic order.

```clojure
[org.clojure/clojure "1.8.0"]
[ring "1.6.2"]
  [ring/ring-core "1.6.2"]
    [clj-time "0.11.0"]
      [joda-time "2.8.2"]
    [commons-fileupload "1.3.2"]
    [commons-io "2.5"]
    [crypto-equality "1.0.0"]
    [crypto-random "1.2.0"]
    [ring/ring-codec "1.0.1"]
      [commons-codec "1.6"]
  [ring/ring-devel "1.6.2"]
    [clj-stacktrace "0.2.8"]
    [hiccup "1.0.5"]
    [ns-tracker "0.3.1"]
      [org.clojure/java.classpath "0.2.3"]
      [org.clojure/tools.namespace "0.2.11"]
  [ring/ring-jetty-adapter "1.6.2"]
    [org.eclipse.jetty/jetty-server "9.2.21.v20170120"]
      [javax.servlet/javax.servlet-api "3.1.0"]
      [org.eclipse.jetty/jetty-http "9.2.21.v20170120"]
        [org.eclipse.jetty/jetty-util "9.2.21.v20170120"]
      [org.eclipse.jetty/jetty-io "9.2.21.v20170120"]
  [ring/ring-servlet "1.6.2"]
```

With `mvn dependency:tree` the dependencies appear in the order in which they are declared.

```
+- org.clojure:clojure:jar:1.8.0:compile
\- ring:ring:jar:1.6.2:compile
   +- ring:ring-core:jar:1.6.2:compile
   |  +- ring:ring-codec:jar:1.0.1:compile
   |  |  \- commons-codec:commons-codec:jar:1.6:compile
   |  +- commons-io:commons-io:jar:2.5:compile
   |  +- commons-fileupload:commons-fileupload:jar:1.3.2:compile
   |  +- clj-time:clj-time:jar:0.11.0:compile
   |  |  \- joda-time:joda-time:jar:2.8.2:compile
   |  +- crypto-random:crypto-random:jar:1.2.0:compile
   |  \- crypto-equality:crypto-equality:jar:1.0.0:compile
   +- ring:ring-devel:jar:1.6.2:compile
   |  +- hiccup:hiccup:jar:1.0.5:compile
   |  +- clj-stacktrace:clj-stacktrace:jar:0.2.8:compile
   |  \- ns-tracker:ns-tracker:jar:0.3.1:compile
   |     +- org.clojure:tools.namespace:jar:0.2.11:compile
   |     \- org.clojure:java.classpath:jar:0.2.3:compile
   +- ring:ring-jetty-adapter:jar:1.6.2:compile
   |  \- org.eclipse.jetty:jetty-server:jar:9.2.21.v20170120:compile
   |     +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
   |     +- org.eclipse.jetty:jetty-http:jar:9.2.21.v20170120:compile
   |     |  \- org.eclipse.jetty:jetty-util:jar:9.2.21.v20170120:compile
   |     \- org.eclipse.jetty:jetty-io:jar:9.2.21.v20170120:compile
   \- ring:ring-servlet:jar:1.6.2:compile
```

Personally I have always taken the Maven behaviour for granted. Whether I have ever needed to rely on the order I don’t remember, but I think there is an element of stronger determinism in it. (Then again, no one has complained so far.)

It would be good to get input from the Leiningen maintainers … is this something that could be changed? I think for users there would be no negative impact, dependencies would just be in an order that’s easier to control instead of alphabetic (arbitrary). If such a change is acceptable then the Pomegranate upstream first needs to make the order information available.

**Comment by hyPiRion** [comment] 2017-08-02 21:15
This is only to ensure that dependencies with duplicate files wins, right? Or is there some other reason I don't know of which would need ordered dependencies? 

I wouldn't mind to order the classpath in the same way Maven does, as long as it's not too complicated to implement. I'm not entirely sure I like the rationale (can't we just avoid duplicating files on the classpath?), although I get that it may happen and that you need to specify the order from time to time. Also, I'm slightly surprised this hasn't come up earlier.

**Comment by technomancy** [comment] 2017-08-02 21:26
> I'm not entirely sure I like the rationale (can't we just > avoid duplicating files on the classpath?)

Unfortunately I don't think this is realistic; the person who would be
hit by this problem is not the person who would cause it, so it's not
really fair to say they need to just fix it in their project.

The real problem is that it's likely that existing projects rely on the
current order.

**Comment by technomancy** [comment] 2017-08-02 21:28
> The real problem is that it's likely that existing projects rely on the current order.

Actually I just took a look at the pomegranate issue and I see that the
unorderedness comes from using a hash-map, so it's effectively
random. Anyone who's relying on the random order is going to see
breakage anyway when they add a dependency, so that shouldn't be
problematic.

**Comment by glts** [comment] 2017-08-05 22:10
I agree that classpath order probably only matters in pathological cases, though such cases do occur in practice. Some ordering situations we came up with that are perhaps not too far-fetched are loading of resources like `logback.xml`, resource bundles, and services that use the `ServiceLoader` API.

To my feeling, being able to control dependency order as with Maven seems the right thing to do. I will follow up at cemerick/pomegranate#86.

**Comment by hyPiRion** [comment] 2017-08-05 23:14
> Unfortunately I don't think this is realistic; the person who would be
> hit by this problem is not the person who would cause it, so it's not
> really fair to say they need to just fix it in their project.

Ah, sorry, this wasn't intended to be directed at anyone in particular. Perhaps "rationale" is the wrong word here, I'm just a bit grumpy classpath ordering matters :p

>  Anyone who's relying on the random order is going to see breakage anyway when they add a dependency, so that shouldn't be problematic.

Yeah, I agree. Also, the hash map ordering has changed previously, so it's very likely that existing users upgrading Leiningen continously would've seen this issue: When the murmur3 hash change happened in Clojure, it broke some Leiningen tests that depended on hash map ordering.

@glts: Thanks for providing examples; those seem very reasonable. I also agree that it's the right thing to do, I just hope it doesn't add too much complexity into the solution. The suggestion on how to solve it in pomegranate seems to make the implementation very straightforward.

**Comment by glts** [comment] 2017-08-18 08:03
Hello @rauhs, there has been some discussion about this issue here and
at cemerick/pomegranate, can you share details on why you need to have
dependency A before dependency B on the classpath?

**Comment by glts** [comment] 2017-08-22 17:07
For the record, I want to retract my earlier statements where I said
that this is a flaw and that Leiningen should replicate the behaviour of
Maven. (I am undecided whether we should retain order or not, both
positions can be argued.)

**Comment by technomancy** [comment] 2017-08-22 18:43
I agree that there's no obvious wrong or right answer for this. In light of that fact, I don't think it should block the 2.8.0 release.

**Comment by vemv** [comment] 2020-08-13 19:03
As a hopefully clear use case, it's currently very risky to add "java source" dependencies in this style:

```clj
[org.clojure/clojure "1.10.1" :classifier "sources"]
```

(be them clojure itself or any 3rd party dep)

...since those will take priority over the actual runnable .jars. So things like `clojure.core/load` will load the wrong resource, e.g. will try to compile a .java file instead of loading the readily available .clj file.

Needless to say .java compilation is quite error-prone and should not be attempted to be automatically done merely because one added a source (which is typically done just for a nicer IDE integration)

So, having the ability to let `:classifier "sources"` or `:classifier "javadoc"` deps be placed at the tail of the calculated classpath would be very nice.

**Comment by technomancy** [comment] 2022-04-08 16:33
Given that this is closed in pomegranate I think we can't do anything here without that.

**Closed by technomancy** 2022-04-08 16:33 UTC
Labels: upstream, investigate
