### ISSUE TITLE
Self-signed certificates for private repositories are broken

### ISSUE THREAD

**Issue by guv** [technomancy/leiningen#1966] opened 2015-08-26 09:09 UTC
Scenario **works** with Leiningen **2.5.0**
Scenario **fails** with Leiningen **2.5.1** and **2.5.2**

With Leiningen 2.5.0 there was no problem using a private repository with a self-signed certificate.
You can either specify `:certificates ["/home/myuser/.lein/myrepository.pem"]` in the `:user` profile in `~/.lein/profiles.clj` or directly in `project.clj`.
I am using the private repository as proxy by specifying `:repositories ^:replace [["myrepo" "https://repo.url/..."]]`.

In both of the latest Leiningen versions, 2.5.1 and 2.5.2, this fails. The reported error depends on the file where the `:certificates` setting is specified.
### `:certificates` in ``~/.lein/profiles.clj`

`lein -U deps :tree` results in:

> Could not transfer artifact <SOMEARTIFACT> from/to myrepo (https://https://repo.url/...): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

With `DEBUG=y lein -U deps :tree` the following stacktrace can be extracted:

> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>  at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:538)
>     org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:216)
>     org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:193)
>     org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom (DefaultArtifactDescriptorReader.java:281)
>     org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor (DefaultArtifactDescriptorReader.java:186)
>     org.sonatype.aether.impl.internal.DefaultDependencyCollector.process (DefaultDependencyCollector.java:412)
>     org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:240)
>     org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:333)
>     sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
>     sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     java.lang.reflect.Method.invoke (Method.java:497)
>     clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:93)
>     clojure.lang.Reflector.invokeInstanceMethod (Reflector.java:28)
>     cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke (aether.clj:720)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invoke (core.clj:624)
>     cemerick.pomegranate.aether$resolve_dependencies.doInvoke (aether.clj:729)
>     clojure.lang.RestFn.applyTo (RestFn.java:137)
>     clojure.core$apply.invoke (core.clj:624)
>     cemerick.pomegranate$add_dependencies.doInvoke (pomegranate.clj:74)
>     clojure.lang.RestFn.invoke (RestFn.java:2088)
>     leiningen.core.classpath/fn (classpath.clj:176)
>     clojure.lang.AFn.applyToHelper (AFn.java:160)
>     clojure.lang.AFn.applyTo (AFn.java:144)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.core$memoize$fn__5097.doInvoke (core.clj:5846)
>     clojure.lang.RestFn.invoke (RestFn.java:436)
>     leiningen.core.classpath$get_dependencies.doInvoke (classpath.clj:306)
>     clojure.lang.RestFn.applyTo (RestFn.java:142)
>     clojure.core$apply.invoke (core.clj:628)
>     leiningen.core.classpath$resolve_dependencies.doInvoke (classpath.clj:350)
>     clojure.lang.RestFn.invoke (RestFn.java:464)
>     leiningen.core.project$load_plugins.invoke (project.clj:691)
>     leiningen.core.project$load_plugins.invoke (project.clj:701)
>     leiningen.core.project$init_project.invoke (project.clj:878)
>     leiningen.core.project$read.invoke (project.clj:952)
>     leiningen.core.project$read.invoke (project.clj:953)
>     leiningen.core.main$_main$fn__6160.invoke (main.clj:388)
>     leiningen.core.main$_main.doInvoke (main.clj:385)
>     clojure.lang.RestFn.invoke (RestFn.java:436)
>     clojure.lang.Var.invoke (Var.java:388)
>     clojure.lang.AFn.applyToHelper (AFn.java:160)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.main$main_opt.invoke (main.clj:315)
>     clojure.main$main.doInvoke (main.clj:420)
>     clojure.lang.RestFn.invoke (RestFn.java:482)
>     clojure.lang.Var.invoke (Var.java:401)
>     clojure.lang.AFn.applyToHelper (AFn.java:171)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.main.main (main.java:37)
### `:certificates` in ``project.clj`

Both `lein -U deps :tree` and `DEBUG=y lein -U deps :tree`  result in:

> java.lang.IllegalArgumentException: No matching field found: getConnectionManager for class org.apache.maven.wagon.providers.http.HttpWagon
>  at clojure.lang.Reflector.getInstanceField (Reflector.java:271)
>     clojure.lang.Reflector.invokeNoArgInstanceMember (Reflector.java:315)
>     leiningen.core.ssl/fn (ssl.clj:91)
>     clojure.lang.AFn.applyToHelper (AFn.java:154)
>     clojure.lang.AFn.applyTo (AFn.java:144)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.core$memoize$fn__5097.doInvoke (core.clj:5846)
>     clojure.lang.RestFn.invoke (RestFn.java:408)
>     clojure.lang.Var.invoke (Var.java:379)
>     leiningen.core.project$load_certificates.invoke (project.clj:764)
>     leiningen.core.project$init_project.invoke (project.clj:878)
>     leiningen.core.project$read.invoke (project.clj:952)
>     leiningen.core.project$read.invoke (project.clj:953)
>     leiningen.core.main$_main$fn__6160.invoke (main.clj:388)
>     leiningen.core.main$_main.doInvoke (main.clj:385)
>     clojure.lang.RestFn.invoke (RestFn.java:436)
>     clojure.lang.Var.invoke (Var.java:388)
>     clojure.lang.AFn.applyToHelper (AFn.java:160)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.core$apply.invoke (core.clj:624)
>     clojure.main$main_opt.invoke (main.clj:315)
>     clojure.main$main.doInvoke (main.clj:420)
>     clojure.lang.RestFn.invoke (RestFn.java:482)
>     clojure.lang.Var.invoke (Var.java:401)
>     clojure.lang.AFn.applyToHelper (AFn.java:171)
>     clojure.lang.Var.applyTo (Var.java:700)
>     clojure.main.main (main.java:37)

**Comment by hyPiRion** [comment] 2015-08-26 09:23
The latest example is an issue that should have been resolved with #1746, which was pushed with 2.5.2. Could you try `:certificates` in `project.clj` with 2.5.2?

**Comment by guv** [comment] 2015-08-26 10:26
You are right the ``IllegalArgumentException`` does not occur in 2.5.2.

I commented the ``:certificates`` option in 2.5.0 and it is still able to connect to the repository and check/download the artifacts. So I guess 2.5.0 did not check whether the certificates are trusted.

Although I specified ``:certificates ["/home/myuser/.lein/myrepo.pem"]`` (same for ``project.clj`` and ``profiles.clj``) Leiningen 2.5.2 results in the following exception on ``lein -U deps :tree":
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

``myrepo.pem`` contains the self-signed certificate in the format:
> -----BEGIN CERTIFICATE-----
  CERTIFCATECONTENT
  -----END CERTIFICATE-----

**Comment by guv** [comment] 2015-09-21 09:18
Additional information:
I reverted to Leiningen 2.5.0 and noticed the following.
In 2.5.0 ```lein deploy``` checks the certificate since I get the ```sun.security.validator.ValidatorException: PKIX path building failed``` when I do not specify the ```:certificates``` property.
After specifying an appropriate ```:certificates``` property in ```.lein/profiles.clj``` ```lein deploy``` works correctly.

**Comment by hyPiRion** [comment] 2015-09-26 13:12
Does this work with Leiningen 2.5.3? I am expecting no difference from 2.5.2, but it would be nice to have this verified.

**Comment by guv** [comment] 2015-09-28 12:36
Yes, there is no difference between 2.5.3. and 2.5.2.

**Comment by hyPiRion** [comment] 2015-10-16 11:47
Heard some more issues related to this, so I want to get this fixed for 2.6.0.

**Comment by hyPiRion** [comment] 2016-01-21 00:13
I am able to reproduce this reliably. Setting up an Archiva instance with a self-signed certificate fails with the same `sun.security.validator.ValidatorException: PKIX path building failed` – which happens when the certificate isn't available.

However, I am unable to reproduce by doing https calls through both raw `java.net` and Apache HttpClient. The code here, for instance, fails if we attempt to connect to a server which uses the self-signed certificate in `"server.pem"`.

```clj
(ns manual-certs.core
  (:require [leiningen.core.ssl :as ssl])
  (:import java.net.URL
           org.apache.http.impl.conn.PoolingHttpClientConnectionManager
           org.apache.http.impl.client.HttpClients
           org.apache.http.client.methods.HttpGet
           org.apache.http.util.EntityUtils))

(defn slurp-https
  [url]
  (let [ssl-ctx (ssl/make-sslcontext (concat
                                      ;;(ssl/read-certs "server.pem") ;; uncomment me
                                      (ssl/default-trusted-certs)))
        conn-mngr (PoolingHttpClientConnectionManager.
                   (#'ssl/map->registry (ssl/https-registry ssl-ctx)))
        client (.. (HttpClients/custom)
                   (setConnectionManager conn-mngr)
                   (build))
        req (HttpGet. url)
        
        _ (println "Executing request" (str (.getRequestLine req)))
        
        resp (.execute client req)
        entity (.getEntity resp)]
    (println "---------------------")
    (println (str (.getStatusLine resp)))
    (EntityUtils/consume entity)))
``` 

If we uncomment the marked line, however, the request works just fine without issues.

Considering there is literally no change from the PoolingHttpClientConnectionManager as shown in the example here and in Leiningen, I've lead to believe that this is either

* an upstream bug in HttpWagon
* That [setPoolingHttpClientConnectionManager](http://maven.apache.org/wagon/apidocs/org/apache/maven/wagon/providers/http/AbstractHttpClientWagon.html#setPoolingHttpClientConnectionManager\(org.apache.http.impl.conn.PoolingHttpClientConnectionManager\)) doesn't retroactively change connection and that previously instantiated wagons retain the original connection manager that is created.

Both needs to be verified of course, but that's my assumption as of right now.

**Comment by hyPiRion** [comment] 2016-01-22 00:22
I have confirmed that this is a bug upstream and submitted apache/maven-wagon#21 which fixes this issue. Now we only have to wait until it's applied and released, so there's unfortunately not much we can do here right now.

**Comment by guv** [comment] 2016-01-22 08:21
Thank you for your work. :)

**Comment by hyPiRion** [comment] 2016-01-23 13:46
I'm sort-of tempted to deploy a fork of maven-wagon, but that would likely cause issues with plugins that depends on maven-wagon transitively. Therefore I'll leave this out of 2.6.0 unless maven-wagon is updated before then.

I'll do a bugfix release immediately when maven-wagon 2.11 is out.

**Closed** 2017-01-31 10:17 UTC
Labels: bug, upstream
