### ISSUE TITLE
Lein 2.8 incompatible with Java 8

### ISSUE THREAD

**Issue by mdrobulis** [technomancy/leiningen#2335] opened 2017-10-23 12:50 UTC
lein version
Leiningen 2.8.0 on Java 1.8.0_91 Java HotSpot(TM) 64-Bit Server VM
```
c:\dev>lein new app lein-test
lein new app lein-test
Generating a project called lein-test based on the 'app' template.
c:\dev>cd lein-test/
cd lein-test/

c:\dev\lein-test>lein repl
lein repl
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Exception in thread "Thread-2" clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
```

**Comment by technomancy** [comment] 2017-10-23 15:24
This is a duplicate of #2321; see the FAQ for a workaround.

**Closed by technomancy** 2017-10-23 15:24 UTC
