### ISSUE TITLE
default clojure version remains 1.10.0

### ISSUE THREAD

**Issue by draeath** [technomancy/leiningen#2675] opened 2020-04-15 02:56 UTC
**Initial debugging steps**
Before creating a report, _especially_ around exceptions being thrown when running Leiningen, please check if the error still occurs after:

- [x] Updating to using the latest released version of Leiningen (`lein upgrade`).
- [x] Moving your `~/.lein/profiles.clj` (if present) out of the way. This contains third-party dependencies and plugins that can cause problems inside Leiningen.
- [x] Updating any old versions of plugins in your `project.clj`, especially if the problem is with a plugin not working. Old versions of plugins like nREPL and CIDER (as well as others) can cause problems with newer versions of Leiningen.
- [x] (If you are using Java 9 or newer), updating your dependencies to their most recent versions. Recent JDK's have introduced changes which can break some Clojure libraries.

**Describe the bug**
On a new and clean installation of lein, lein defaults to using clojure 1.10.0 instead of 1.10.1. It appears that this was intended to be bumped forward in lein 2.9.2 but was either missed or rolled back (without being noted in the release description for 2.9.3, from what I can tell): [Bump to Clojure 1.10.1. (Phil Hagelberg)](https://github.com/technomancy/leiningen/releases/tag/2.9.2)

**To Reproduce**
1. Fresh installation of 2.9.3
2. Verify on 2.9.3 with `lein version`
3. Check with `lein repl`

**Actual behavior**
clojure 1.10.0 is downloaded and used by default

**Expected behavior**
clojure 1.10.1 is downloaded and used by default

**Link to sample project**
N/A

**Logs**
N/A

**Environment**
- Leiningen Version: 2.9.3
- Leiningen installation method: bin/lein from stable branch (d4aec40)
- JDK Version: openjdk version "11.0.6" 2020-01-14 (build 11.0.6+10-suse-3.1-x8664)
- OS: openSUSE x86-64 Tumbleweed 20200409

**Additional context**
N/A

**Comment by pmonks** [comment] 2020-04-17 21:13
This may be the root cause of https://github.com/noisesmith/lein-git-info-edn/issues/3.

**Comment by nihilismus** [comment] 2020-04-20 14:23
Also discussed in commit https://github.com/technomancy/leiningen/commit/d4aec407c677a9672e2b0150c31e913bc05c429a#commitcomment-37921092

**Comment by technomancy** [comment] 2020-07-08 19:06
This should be fixed with 2.9.4 in 0e8839e.

**Closed by technomancy** 2020-07-08 19:06 UTC
