### ISSUE TITLE
ClassNotFoundException: leiningen.core.project$reduce_dep_step

### ISSUE THREAD

**Issue by mmower** [technomancy/leiningen#2080] opened 2016-02-07 21:53 UTC
After updating from 2.5.3 to 2.6.0 my ring server no longer starts.

Alia:sortapi matt$ lein ring server-headless
Exception in thread "main" java.lang.ClassNotFoundException: leiningen.core.project$reduce_dep_step, compiling:(/private/var/folders/3w/h1j_8qvs0k59mhmx5n72p6840000gn/T/form-init4229607758209986319.clj:1:10218)
	at clojure.lang.Compiler.load(Compiler.java:7386)

Reverting to 2.5.3 seems to be okay. Lein ancient tells me everything up to date. 

(full stack trace: https://gist.githubusercontent.com/mmower/21646cd1f88dd04f68c7/raw/e60db0adbf0f30c622c188280d9e9e284ad35231/gistfile1.txt)

I've also included my project.clj in case there are any clues there:

[project.clj.txt](https://github.com/technomancy/leiningen/files/120942/project.clj.txt)

**Comment by hyPiRion** [comment] 2016-02-07 22:04
Duplicate of #2079. I will release 2.6.1 in a few hours, so it should be resolved when you update to 2.6.1.

**Closed by hyPiRion** 2016-02-07 22:04 UTC
