### ISSUE TITLE
Problem with typing  square brackets in Leiningen

### ISSUE THREAD

**Issue by wygotsky** [technomancy/leiningen#1803] opened 2015-01-18 10:17 UTC
Hello everyone, I am new to Clojure and Leiningen and I am also new to coding. This is my issue:

When I open the Leiningen REPL, I have difficulties typing square brackets. I use a Lenovo Thinkpad E555 running with  Windows  7. The keyboard layout  is German (QWERTZ). Normally, square brackets are produced by typing AltGr+8 or AltGr+9. But this  doesn't  work in the Leiningen  REPL. I have press AltGr and 8 twice (!) in order to produce an opening square bracket [. By complete chance I found  out how to producde the  closing bracket ]. I have to type AltGr+8 and then 9 while keeping AltGr pressed.

As you can imagine, this is quite annoying. 

When I open an REPL with "java -cp clojure-1.6.0.jar clojure.main" everything works  just as it should.

I had the  same issue in Scala's REPL, which  I could  resolve after someone gave me a hint. Apparently, there is a bug  in jline-2.12.jar in the  scala/lib. I replaced  it  with jline-2.11 and everything worked  fine.

Any idea, how I can solve the  issue with Leiningen?

Greetings,

Wygotsky

**Comment by hyPiRion** [comment] 2015-01-18 10:49
This is a duplicate of #1574 – there are ways to replace jline-2.12 with 2.11, but they are not properly documented yet. #1795 has a rough outline on how to do it.

**Closed by hyPiRion** 2015-01-18 10:49 UTC

**Comment by leifericf** [comment] 2021-11-23 12:42
I'm experiencing a similar issue on macOS 11.6, when using the the REPL via [iTerm2](https://iterm2.com). I'm using Leiningen 2.9.8 on Java 15.0.1. Using an Apple Magic Keyboard (QWERTY) with Norwegian layout.

Square brackets are typed using Option + 8 (`[`) and Option + 9 (`]`). This was working fine in the REPL, until I changed my Meta-key (in my iTerm2 Profile settings) to `Left Option Key = Esc+`, which was necessary to get the Meta-key to function properly in CIDER in Emacs. After this change, it is no longer possible to type square brackets in the REPL.

I'm not sure whether this is the same issue (duplicate) or a slightly different issue. I'm also not sure whether this is an issue with the REPL, iTerm2 or something else. Any advice would be greatly appreciated.
