### ISSUE TITLE
Leiningen doesn't seem to be resolving dependences of type "test-jar"

### ISSUE THREAD

**Issue by mikera** [technomancy/leiningen#1975] opened 2015-09-05 02:34 UTC
Perhaps I'm doing something wrong - but I'm having trouble including a dependency of type "test-jar" in a project. I have verified that this works with the same dependency in Maven.

Here's the project.clj:

``` clojure
(defproject clatrix/clatrix "0.5.1-SNAPSHOT"
  :description "Because using matrices in Clojure needs to not suck."
  :url "http://tel.github.com/clatrix"
  :license {:name "MIT License"
            :url "http://www.opensource.org/licenses/MIT"}
  :resource-paths ["native"]
  :plugins [[lein-expectations "0.0.8"]]

  :dependencies [[org.clojure/clojure "1.8.0-alpha4"]
                 [slingshot "0.12.2"]
                 [org.jblas/jblas "1.2.3"]
                 [net.mikera/core.matrix "0.40.0"]]

  :profiles {:dev {:dependencies [[criterium/criterium "0.4.3"]
                                  [net.mikera/core.matrix "0.40.0" :type "test-jar"]
                                  [expectations "2.1.1"]]}})
```

And here's the result of `lein deps :tree`

```
 [criterium "0.4.3" :scope "test"]
 [expectations "2.1.1" :scope "test"]
   [joda-time "2.7" :scope "test"]
   [junit "4.12" :scope "test"]
     [org.hamcrest/hamcrest-core "1.3" :scope "test"]
   [org.clojure/clojurescript "0.0-3196" :scope "test"]
     [com.google.javascript/closure-compiler "v20150126" :scope "test"]
       [args4j "2.0.26" :scope "test"]
       [com.google.code.findbugs/jsr305 "1.3.9" :scope "test"]
       [com.google.code.gson/gson "2.2.4" :scope "test"]
       [com.google.guava/guava "18.0" :scope "test"]
       [com.google.javascript/closure-compiler-externs "v20150126" :scope "test"]
       [com.google.protobuf/protobuf-java "2.5.0" :scope "test"]
       [com.google.truth/truth "0.24" :scope "test"]
     [org.clojure/data.json "0.2.6" :scope "test"]
     [org.clojure/google-closure-library "0.0-20140718-946a7d39" :scope "test"]
       [org.clojure/google-closure-library-third-party "0.0-20140718-946a7d39" :scope "test"]
     [org.clojure/tools.reader "0.9.1" :scope "test"]
     [org.mozilla/rhino "1.7R5" :scope "test"]
 [net.mikera/core.matrix "0.40.0" :scope "test"]
   [org.clojure/tools.macro "0.1.5" :scope "test"]
 [org.clojure/clojure "1.8.0-alpha4"]
 [org.clojure/tools.nrepl "0.2.10" :exclusions [[org.clojure/clojure]]]
 [org.jblas/jblas "1.2.3"]
 [slingshot "0.12.2"]
```

So it looks like the main `core.matrix` is being included, but not the "test-jar" artifact.

**Comment by mikera** [comment] 2016-08-12 05:22
Any chance of resolving this one? Currently it is making it impossible to do proper testing for independent core.matrix implementations with Leiningen - only workaround is to recommend Maven!

**Comment by cprice404** [comment] 2016-08-12 15:59
Have you tried using `classifier`?  We use test jars quite a bit in our projects, e.g.:

https://github.com/puppetlabs/puppetserver/blob/6e7d274db90f4f22d87caec545e541d36a99f64c/project.clj#L112-L114

And lein has been working fine for us with this pattern.

**Comment by mikera** [comment] 2016-08-13 09:47
Interesting - that may be a workaround for now.

I still think this is a valid issue, as the same pattern with `type` works in Maven

**Comment by glts** [comment] 2019-05-15 19:27
This is by design, Leiningen uses a different and (arguably more consistent) notation. Leiningen (ie, Pomegranate) has no notion of `:type` at all here.

A test-jar-type dependency in Maven corresponds to a dependency with classifier `tests` in Leiningen.

    <dependency>
        <groupId>net.mikera</groupId>
        <artifactId>core.matrix</artifactId>
        <version>0.40.0</version>
        <type>test-jar</type>
    </dependency>



    [net.mikera/core.matrix "0.40.0" :classifier "tests"]

Both of these resolve to the artifact `net/mikera/core.matrix/0.40.0/core.matrix-0.40.0-tests.jar`.

**Comment by glts** [comment] 2019-06-27 06:23
* In Leiningen/Pomegranate, `:classifier` always maps to the suffix before the file extension, and `:extension` always maps to the file extension.
* In Maven, however, `classifier` maps to the classifier suffix, but `type` can determine both classifier suffix and file extension, and in a completely opaque manner. For example, type `test-jar` results in a classifier suffix `tests` (!) and file extension `jar`.

You can see that supporting a `:type` attribute in Leiningen would add no value whatsoever, it would only complicate a simple design by reproducing an ugly corner of Maven. In any case such a feature request would better be directed to Pomegranate first. That is why I think we shouldn’t do anything here, and we can close this issue.

**Comment by technomancy** [comment] 2019-06-27 23:30
I agree; I expect the behavior described in Maven was added early on and had to be kept around for backwards-compatibility. Using `:classifier` is the way to go here.

**Closed by technomancy** 2019-06-27 23:30 UTC
Labels: bug
