### ISSUE TITLE
lein 2.9.0 breaks order dependent AOT

### ISSUE THREAD

**Issue by madstap** [technomancy/leiningen#2540] opened 2019-02-26 06:39 UTC
**Describe the bug**
I have some code that's dependent on the ordering of nses in the :aot key. 1.9.0 breaks this.

**To Reproduce**

```
(ns rpro.foo
  (:gen-class :name rpro.foo))
```

```
(ns rpro.bar

  ;; I thought either of these would fix it,
  ;; but they seem to have no effect.
  (:require [rpro.foo])
  (:import (rpro foo))

  (:gen-class :name rpro.bar
              :methods [[getFoo [] rpro.foo]]))
```

```
(defproject rpro "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.0"]]
  :aot [rpro.foo rpro.bar])
```

Run `lein uberjar` 

**Actual behavior**
```
Unexpected error macroexpanding clojure.core/gen-class at (rpro/bar.clj:1:1).
Exception in thread "main" Unexpected error macroexpanding clojure.core/gen-class at (rpro/bar.clj:1:1).
...
Caused by: java.lang.ClassNotFoundException: rpro.foo
```

**Expected behavior**
The code should compile.

**Link to sample project**
https://github.com/madstap/lein-aot-repro
(You can change the lein version at the top of the dockerfile.)

**Additional context**
The behavior changed in 2.9.0.

**Comment by technomancy** [comment] 2019-02-26 16:31
I'm pretty sure this is fixed on master with bfe5c53 but if you are still seeing it after upgrading from 2.9.0 feel free to reopen.

**Closed by technomancy** 2019-02-26 16:31 UTC

**Comment by technomancy** [comment] 2019-02-27 00:40
The fix is on the stable 2.9.1 release now.

**Comment by madstap** [comment] 2019-02-27 02:10
That fixed it, nice!

**Comment by michaelsbradleyjr** [comment] 2020-05-09 00:25
I'm experiencing this on 2.9.3, maybe there was a regression? Can this issue be re-opened?

**Comment by ccqpein** [comment] 2020-05-28 15:48
Looks like I have same issue today, something revert?
