### ISSUE TITLE
Lein release does not respect version precedence

### ISSUE THREAD

**Issue by arichiardi** [technomancy/leiningen#2043] opened 2015-12-17 03:47 UTC
Hello guys, it is the first time I use `lein release` so I might be doing something wrong.

I thought that I was on `0.1.3-SHAPHOT` and run `lein release :alpha` would bring me to `0.1.3-alpha`. At the of the day, SemVer says:

> Major, minor, and patch versions are always compared numerically. Example: 1.0.0 < 2.0.0 <
> 2.1.0 < 2.1.1. When major, minor, and patch are equal, a pre-release version has lower 
> precedence than a normal version. Example: 1.0.0-alpha < 1.0.0.

This did not happen and I directly deployed `0.1.3`.

I have not explored whether it is just `:alpha` the problem, but I can make some test with `:beta` and `:rc` as well.

**Comment by hyPiRion** [comment] 2015-12-17 10:00
Hi there,

I believe this is a documentation issue. I'm pretty sure this would've worked if you specified `0.1.3-alpha1-SNAPSHOT` -- in which case `lein release :alpha` would release 0.1.3-alpha1 and bump the version to `0.1.3-alpha2`.

**Comment by arichiardi** [comment] 2015-12-17 17:01
Yes but then how to generate `0.1.3-alpha-snapshot` with lein release. I can change the doc no problem, just to understand the process

**Comment by arichiardi** [comment] 2015-12-18 01:50
Not even with `-SNAPSHOT` works, I had `0.1.4-alpha1-SNAPSHOT` and after `lein release :alpha` I got:

```
* 0f98742 (HEAD -> master, tag: 0.1.4) Version 0.1.4
* b56f6d6 (origin/master) Version 0.1.4-alpha1-SNAPSHOT
```

**Comment by hyPiRion** [comment] 2015-12-18 08:49
Alright, then this seems to be a bug.

**Comment by cprice404** [comment] 2015-12-24 04:14
So, the expected behavior is that with an initial version of `0.1.4-alpha1-SNAPSHOT`, a `lein release :alpha` would result in an actual release of `0.1.4-alpha1` and then bump the version to `0.1.4-alpha2-SNAPSHOT`?

That is the behavior that I would expect, but the documentation doesn't really explain the intended behavior for the alpha/beta/rc stuff.

This is related to some of the ideas I'm playing with for #2049 and I think it's possible to make it work the way I described above, but I'm not sure if that would necessarily end up being backward-compatible with the existing behavior for alpha/beta/rc.

**Comment by cprice404** [comment] 2015-12-24 04:15
Here are some examples of how it works right now:

```
user=> (release/bump-version "1.0.0-SNAPSHOT" :alpha)
"1.0.0-alpha1"
user=> (release/bump-version "1.0.0-alpha2" :alpha)
"1.0.0-alpha3"
user=> (release/bump-version "1.0.0-alpha2-SNAPSHOT" :alpha)
"1.0.0-alpha1"
```

**Comment by arichiardi** [comment] 2015-12-24 04:19
I don't think you question is for this issue...in any case the behavior is not right because for instance your first example releases (tags and deploys) `1.0.0` which of course is not what you want as you will be working on `alpha1`

**Comment by arichiardi** [comment] 2015-12-24 04:23
Actually from you examples I understand that the problem of this issue is not in `release/bump-version` but upper in the chain of `:release-tasks`

**Comment by cprice404** [comment] 2015-12-24 14:22
I think the issue is in `bump-version`, unless I'm misunderstanding something.  `bump-version` gets called twice during the `release` task, once via:

`["change" "version" "leiningen.release/bump-version" "release"]`

and then the release happens, and then it gets called again as:

`["change" "version" "leiningen.release/bump-version"]`

In the second call, the final `level` argument is omitted, so it defaults to `:patch`.  So we can experiment with this without doing an actual release by just running commands like:

```
$  lein pprint :version
"0.4.1-alpha1-SNAPSHOT"
$ lein change version "leiningen.release/bump-version" :release && lein pprint :version
"0.4.1"
$ lein change version "leiningen.release/bump-version" :patch && lein pprint :version
"0.4.2-SNAPSHOT"
```
So you can see that the call to `bump-version :release` is changing `0.4.1-alpha1-SNAPSHOT` to `0.4.1`, and IMO that is the bug here.  It should instead change it to `0.4.1-alpha1`.  Then you would not end up with an `0.4.1` release being deployed.

Am I misunderstanding?

**Comment by cprice404** [comment] 2015-12-24 17:06
I filed PR #2050, which I believe would address this issue.

**Comment by arichiardi** [comment] 2015-12-24 17:19
Yes that's exactly the problem then, I was wrong :smile: Thanks for having taken care of it!

**Comment by hyPiRion** [comment] 2016-01-05 18:28
Fixed on master by #2050.

**Closed by hyPiRion** 2016-01-05 18:28 UTC
Labels: bug

**Comment by arichiardi** [comment] 2016-01-21 20:23
@hyPiRion and @cprice404 this is still not working as I expect but feel free to disagree:

```
$ lein pprint :version
"0.1.5-SNAPSHOT"
$ lein change version "leiningen.release/bump-version" :alpha && lein pprint :version
"0.1.5-alpha1-SNAPSHOT" <- OK
```

But:

```
$ lein pprint :version
"0.1.5-SNAPSHOT"
$ lein release :alpha
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
[master 5b4e968] Version 0.1.5
 1 file changed, 1 insertion(+), 1 deletion(-)
```

If I want a `alpha1-SNAPSHOT` I have to:

`lein change version "leiningen.release/bump-version" :alpha && lein pprint :version`

which correctly modifies things, then use `lein release :alpha` again and have:
```
* 220bd84 (HEAD -> master) Version 0.1.5-alpha1
* 90a6b0b Version 0.1.5-alpha1-SNAPSHOT
```

**Comment by arichiardi** [comment] 2016-01-21 20:25
Maybe what I am asking is a `lein version :alpha` skipping the release process, but I can make an alias for that.

**Comment by cprice404** [comment] 2016-01-21 20:29
@arichiardi my expectation would be that if you were starting off with `0.1.5-SNAPSHOT` and wanting to do `alpha` releases, you'd do a single execution of `lein change version "leiningen.release/bump-version :alpha` first (or just edit by hand to end up with `0.1.5-alpha1-SNAPSHOT`).  From that point forward I would think you could run `lein release :alpha` as many times as you liked and it should keep bumping the alpha qualifier each time.

That ^^ would be my current definition of "expected behavior"... if it's not working like that, then I'd consider that a bug in what I was attempting to achieve.  It's also certainly debatable as to whether my definition of "expected behavior" aligns with everyone else's :)

**Comment by arichiardi** [comment] 2016-01-21 20:34
Yes I was thinking about it too and I agree it is the way to go, so no bug here, and thank you for patching (and answering!)
