### ISSUE TITLE
lein deploy clojars credentials not being read from env vars

### ISSUE THREAD

**Issue by marcomorain** [technomancy/leiningen#2307] opened 2017-09-05 16:29 UTC
Given the following `project.clj`

```clojure
(defproject deploy-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :repositories [["clojars" {:url "https://clojars.org/repo"
                              :username :env/clojars_username
                              :password :env/clojars_password
                              :sign-releases false}]]
  :dependencies [[org.clojure/clojure "1.8.0"]]
  :main ^:skip-aot deploy-test.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

and running this command:

```
$ CLOJARS_USERNAME=marcomorain CLOJARS_PASSWORD=secret lein deploy clojars
```

I get the following output:

```
No credentials found for clojars
See `lein help deploying` for how to configure credentials to avoid prompts.
Username:
```

With the prompt waiting for Clojars credentials. I would expect the credentials to be read from the environment.

The following works:

```clojure
(defproject deploy-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :repositories [["snapshots" {:url "https://clojars.org/repo"
                               :username :env/clojars_username
                               :password :env/clojars_password
                               :sign-releases false}]]
 
  
     
  :dependencies [[org.clojure/clojure "1.8.0"]]
  :main ^:skip-aot deploy-test.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

deploying like this:

```
CLOJARS_USERNAME=marcomorain CLOJARS_PASSWORD=secret lein deploy snapshots
```

**Comment by marcomorain** [comment] 2017-09-05 16:29
`Leiningen 2.7.1 on Java 1.8.0_74 Java HotSpot(TM) 64-Bit Server VM`

**Comment by glts** [comment] 2017-09-09 11:14
Looked into this briefly. The cause is that the `:deploy-repositories`
setting overrides the `:repositories` setting, via `merge`:

https://github.com/technomancy/leiningen/blob/2.7.1/src/leiningen/deploy.clj#L69-L70

The default value of `:deploy-repositories` includes an entry for
`"clojars"` with `:username`/`:password` keys with value `:gpg`:

https://github.com/technomancy/leiningen/blob/2.7.1/leiningen-core/src/leiningen/core/project.clj#L289-L290

Thus the workaround is specifying credentials at the
`:deploy-repositories` key.

```
:deploy-repositories [["clojars" {:url "https://clojars.org/repo"
                                  :username :env/clojars_username
                                  :password :env/clojars_password
                                  :sign-releases false}]]
```

**Comment by technomancy** [comment] 2017-09-11 21:00
Since we have a workaround we can drop this from the 2.8.0 milestone.

I think it would make sense to merge the values from `:repositories` and `:deploy-repositories` as long as the `:url` matches.

**Comment by zamaterian** [comment] 2019-05-21 10:28
Notice that lein deploy - converts the env vars to uppercase, so `:env/some_password` should be exported as `export SOME_PASSWORD=foo` 
 Leiningen 2.9.1

**Comment by dAnjou** [comment] 2019-09-13 15:47
Hi, this is still happeningfor me in version 2.9.1 exactly as OP has described even with using @glts' code.

**Comment by slr71** [comment] 2020-04-07 18:05
I ran into something that looked a lot like this when I tried to deploy something today. It turned out to be caused by my `credentials.clj.gpg` file. I was using `https://clojars.org/repo` as the Clojars URL, which has been changed to `https://repo.clojars.org`. Updating that file fixed the problem.

**Comment by lungsi** [comment] 2020-05-09 22:01
I have to say that @slr71 's observation of changing to `https://repo.clojars.org` was the only way I could solve my first deployment on clojars after spending my afternoon figuring out why `lein deploy` returned  `Failed to deploy artifacts` and `Access denied to: https://clojars.org/<repo-name>/<lib-name>/<version>/<lib-name-version.jar>`.

If it was up to me I will pin this observation :-)

**Comment by technomancy** [comment] 2022-04-22 17:53
> I think it would make sense to merge the values from :repositories and :deploy-repositories as long as the :url matches.

So apparently we already do this.

The problem is that the deploy task has to decide which to prefer between :repositories vs :deploy-repositories when they conflict. Since :deploy-repositories is more specific, it's given preference. But the value from :deploy-repositories comes from leiningen's defaults, while the value from :repositories comes from the user's override, so it would be better to prefer :repositories. The problem is by the time it gets to the deploy task, there's no way to tell where each one came from.

I think this is an inherent problem with supporting both :repositories and :deploy-repositories; it would have been better if instead of :deploy-repositories, we just had :repositories inside a :deploy profile, but at this point, I don't think it can be fixed without breaking backwards compatibility.

IMO the workaround given above (specify :deploy-repositories instead of :repositories) is the best we can do, which is kind of a drag, but I don't see another way.

**Comment by technomancy** [comment] 2022-04-22 17:56
We can reopen if anyone has other suggestions but I'm not seeing any.

**Closed by technomancy** 2022-04-22 17:56 UTC
Labels: usability
