### ISSUE TITLE
Leiningen native paths issue (for LWJGL, maybe others)

### ISSUE THREAD

**Issue by noncom** [technomancy/leiningen#1961] opened 2015-08-21 17:36 UTC
**UPDATE:** Okay, I am seeing this issue is not getting picked up. Probably because it needs to be reformulated. The original message will be available under the tearline.

My project depends on LWJGL and it involves working with the LWJGL native libraries. I have found that Leiningen is searching for the native libs in the `project/target/native/windows/x86_64` directory.  However, in reality the native libs get extracted into `project/target/native/windows`. If I manually copy the `dll`s from the latter to the former, then the project, launched with Leiningen can see the `dll`s and use them.

Apparently this is an issue in how Leiningen manages the paths and needs to be corrected.

Below is a link to an example project. The issue was successfully reproduced on Windows and Mac. Please also read the reproduction instruction because it describes precise steps of reproducing the problem. How the problem manifests itself depends on the sequence of actions taken.

* sample project https://github.com/noncom/test-natives

**REPRODUCTION INSTRUCTION**

***I. The Original Failure***

See how Leiningen fails to find the `dll`s it extracts.

* remove the `target` and `bin` directories
2. `lein clean`
3. add `:native-path "target/native/native/windows"` to the `project.clj`
4. `lein repl`
5. `(require 'test-natives.core)`
6. It fails to find the dep

If you go to the target dir, there's a strange thing. The dlls are lying in this actual location: `target\native\native\windows\native\windows\`..this looks very wrong...

***II. The original guilt of the `:native-path`***

This will prove that the `:native-path` parameter does not behave correctly:

* manually remove the `target` and `bin` directories
2. `lein clean`
3. `lein repl`
4. exit lein repl back to command line
5. add `:native-path "target/native/native/windows"` to the `project.clj`
6. `lein repl`
7. `(require 'test-natives.core)`
8. It works.

Somehow specifying `:natives-path` before the first creation of `target` wreaks havoc on the directory structure.

***III. The Final Disclosure***

How to understand what is going on:

* manually remove the `target` and `bin` directories
2. `lein clean`
5. add `:native-path "target/native/a/b/c/d/native/windows"` to the `project.clj`
3. `lein repl`
4. `(require 'test-natives.core)` fail!
4. exit lein repl back to command line
3. examine the directory structure and find dlls at `target\native\a\b\c\d\native\windows\native\windows\` - the actual path differs from the one specified in `project.clj` by having an additional `\native\windows\` at the end. alright.
9. change `:native-path "target/native/a/b/c/d/native/windows"` to  `:native-path "target/native/a/b/c/d/native/windows/native/windows"` the `project.clj`
6. `lein repl`
7. `(require 'test-natives.core)`
8. It works

Obviously this is a bug in Leiningen. It treats the `:native-paths` parameter differently in cases of the first and subsequent runs.

_-------------- tearline --------------_

Working with LWJGL in Leiningen, I have stepped into some strange errors on about how Leiningen works with native libraries paths. As I work through CounterClockWise, I first reported the problem to its issue tracker, but after some research it became evident that the problem is of Leiningen origin.

As the description of the problem is rather extensive, I think I won't copy-paste it here and instead provide the description via link to the CCW issue.

* original problem description: https://github.com/laurentpetit/ccw/issues/836#issue-99408999
* Leiningen bug identification and statement: https://github.com/laurentpetit/ccw/issues/836#issuecomment-133457004
* sample project for reproduction: https://github.com/noncom/test-natives

**Comment by hyPiRion** [comment] 2016-01-23 18:03
Alright, this is inconsistent because the native path is not cleaned up if `:native-path` has been changed. Neither does it clean up if the native dependencies themselves change. I'm working on a fix for this, which should be provided with 2.6.0.

It seems like the native paths themselves works as intended for native dependencies (mostly because of what's discussed over at https://github.com/technomancy/leiningen/issues/898#issuecomment-11786405), but as outlined in https://github.com/rogerallen/hello_lwjgl it seems like lwjgl has a very strange packaging format that cannot be extracted by Leiningen itself.

**Closed** 2016-02-04 23:05 UTC
Labels: bug
