### ISSUE TITLE
lein search fails when downloading clojars.org index

### ISSUE THREAD

**Issue by wbthomason** [technomancy/leiningen#2073] opened 2016-01-24 18:05 UTC
I've recently made fresh installs of leiningen on machines running OSX and Arch Linux, using their respective package managers (homebrew and the AUR). When I run `lein search ring`, leiningen updates its package indices, as expected. However, the program appears to deadlock or hang on "Downloading https://clojars.org/repo/.index/nexus-maven-repository-index.properties". 

By looking in .lein, I've confirmed that there is a folder made for the clojars.org index, and it appears to have all the necessary files other than `timestamp`, based on a loose comparison to the directory created for the maven.org repo. If I copy `timestamp` over to the clojars folder, `lein search` no longer hangs, but it also doesn't appear to search the clojars.org repo (as evinced by the lack of any reference to ring-clojure/ring in the results for `lein search ring`. Further, by looking at network traffic while the initial `lein search` is running, it seems that it only downloads 4KB in total, which seems to indicate that it isn't downloading anything other than the .properties file. 

This seems like the kind of error which would either be highly reported or due to problems with system configuration on my end. As it doesn't appear to have been reported (that I could find), it seems that it may be a problem with my system. However, given that I've observed it across 3 separate machines running 2 different OSes, and @aml3 has observed the same on his Arch machine, it seems reasonable that it may be a larger issue. I've also tried letting this run overnight, in case it was just an issue of speed (as in #534), but with no change. All other functionality of leiningen that I've tested (including `lein deps`) has seemed to work correctly.

This is the output of the command on OSX:
```
lein search ring
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
Updating the search index. This may take a few minutes...
Downloading https://repo1.maven.org/maven2/.index/nexus-maven-repository-index.properties
100.0% complete
Downloading https://repo1.maven.org/maven2/.index/nexus-maven-repository-index.gz
100.0% complete
Updating the search index. This may take a few minutes...
Downloading https://clojars.org/repo/.index/nexus-maven-repository-index.properties

```
When I use Ctrl+\ to get a stack trace, it has this output:
```
^\2016-01-24 13:01:09
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode):

"Index-BottleWarmer-clojars" #15 daemon prio=5 os_prio=31 tid=0x00007fb923800000 nid=0xae03 waiting on condition [0x0000700001558000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.apache.maven.index.context.DefaultIndexingContext$1.run(DefaultIndexingContext.java:1189)
	at java.lang.Thread.run(Thread.java:745)

"Index-BottleWarmer-central" #14 daemon prio=5 os_prio=31 tid=0x00007fb925e98000 nid=0xac03 waiting on condition [0x0000700001455000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.apache.maven.index.context.DefaultIndexingContext$1.run(DefaultIndexingContext.java:1189)
	at java.lang.Thread.run(Thread.java:745)

"com.google.inject.internal.util.$Finalizer" #13 daemon prio=5 os_prio=31 tid=0x00007fb924fb9800 nid=0x7317 in Object.wait() [0x00007000012cf000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000074158e8a0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x000000074158e8a0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at com.google.inject.internal.util.$Finalizer.run(Finalizer.java:143)
	at java.lang.Thread.run(Thread.java:745)

"AWT-AppKit" #11 daemon prio=5 os_prio=31 tid=0x00007fb9233a6000 nid=0x220b runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007fb923046800 nid=0x4803 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fb923044000 nid=0x4603 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fb923043000 nid=0x4403 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fb923041800 nid=0x4203 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fb924000000 nid=0x360f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fb92385a800 nid=0x3003 in Object.wait() [0x000070000092e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x000000074033f0b8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fb92385a000 nid=0x2e03 in Object.wait() [0x000070000082b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x000000074033f0f8> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=31 tid=0x00007fb92300d000 nid=0xc07 waiting on condition [0x0000700000214000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007a6d7e5e8> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at clojure.core$promise$reify__6779.deref(core.clj:6816)
	at clojure.core$deref.invoke(core.clj:2206)
	at leiningen.search$http_resource_fetcher$fn__5668.invoke(search.clj:98)
	at leiningen.search.proxy$java.lang.Object$ResourceFetcher$93824c0b.disconnect(Unknown Source)
	at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at leiningen.search$update_index.invoke(search.clj:110)
	at leiningen.search$search$fn__5733.invoke(search.clj:222)
	at leiningen.search$search.invoke(search.clj:222)
	at leiningen.search$search.invoke(search.clj:208)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:632)
	at leiningen.core.main$partial_task$fn__6030.doInvoke(main.clj:261)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at leiningen.core.main$apply_task.invoke(main.clj:311)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:317)
	at leiningen.core.main$_main$fn__6096.invoke(main.clj:390)
	at leiningen.core.main$_main.doInvoke(main.clj:383)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.main$main_opt.invoke(main.clj:316)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at clojure.lang.Var.invoke(Var.java:394)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)

"VM Thread" os_prio=31 tid=0x00007fb923857800 nid=0x2c03 runnable

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007fb923805800 nid=0x1607 runnable

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007fb923806800 nid=0x2603 runnable

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007fb923807000 nid=0x2803 runnable

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007fb923807800 nid=0x2a03 runnable

"VM Periodic Task Thread" os_prio=31 tid=0x00007fb9238bf800 nid=0x4a03 waiting on condition

JNI global references: 279

Heap
 PSYoungGen      total 382976K, used 327106K [0x0000000795580000, 0x00000007b4a00000, 0x00000007c0000000)
  eden space 381440K, 85% used [0x0000000795580000,0x00000007a9376508,0x00000007aca00000)
  from space 1536K, 98% used [0x00000007b4880000,0x00000007b49fa588,0x00000007b4a00000)
  to   space 10240K, 0% used [0x00000007b3600000,0x00000007b3600000,0x00000007b4000000)
 ParOldGen       total 177152K, used 114009K [0x0000000740000000, 0x000000074ad00000, 0x0000000795580000)
  object space 177152K, 64% used [0x0000000740000000,0x0000000746f56570,0x000000074ad00000)
 Metaspace       used 53512K, capacity 61636K, committed 61824K, reserved 1097728K
  class space    used 10840K, capacity 13653K, committed 13696K, reserved 1048576K

```

**Comment by hyPiRion** [comment] 2016-01-24 22:09
Yeah, it does not seem to work on master either.

**Comment by ackalker** [comment] 2016-02-15 21:40
I think the cause may be that the HTTP response for `https://clojars.org/repo/.index/nexus-maven-repository-index.properties` does not contain a `Content-Length` header, at least according to `http/get`.

Adding an (ugly: it appears as if execution never gets past the first part of the `let` form) hack to [these lines](https://github.com/technomancy/leiningen/blob/2ca63f0084091d7799482ebe97cb60b8f17d76c9/src/leiningen/search.clj#L100-L105) in `src/leiningen/search.clj`, I was able to get some more info.

```clojure
        (println "Downloading" (str @base-url "/" name))
        (let [dummy1 (println "before (http/get ...)")
              r (http/get (str @base-url "/" name)
                           {:throw-exceptions false :as :stream})
              dummy2 (println (keys r))
              dummy3 (println (:headers r))
              dummy4 (println "status:" (:status r))
              dummy5 (println "content-length:" (get (:headers r) "content-length"))
              s (leiningen.search.extstream.
                 (:body r)
                 (Long/parseLong (get (:headers r) "content-length")))]

```

```
$ ( cd leiningen-core; lein bootstrap )
$ bin/lein search ring
Updating the search index. This may take a few minutes...
Downloading https://repo1.maven.org/maven2/.index/nexus-maven-repository-index.properties
before (http/get ...)
(:status :headers :body :request-time :trace-redirects :orig-content-encoding)
{X-Cache HIT, HIT, Fastly-Debug-Digest 78d61ed543914a52f25a7d8abc6994ddad8f6072776154c6472b9ff4d7b41c52, X-Timer S1455568360.251104,VS0,VE0, x-amz-meta-last-modified-epoch 1453670376726, Age 84620, Via [1.1 varnish 1.1 varnish], Content-Type text/plain, Content-Length 1130, Connection close, X-Checksum-MD5 cd51b2ba384151b869b4b56a6f1ff432, Accept-Ranges bytes, ETag "cd51b2ba384151b869b4b56a6f1ff432", X-Cache-Hits 1, 1, Date Mon, 15 Feb 2016 20:32:40 GMT, X-Checksum-SHA1 99700ca775951d0be6690679277f6b04a7ad5df4, Last-Modified Sun, 24 Jan 2016 21:19:36 GMT, X-Served-By cache-iad2149-IAD, cache-lcy1125-LCY}
status: 200
content-length 1130
ext-init
100.0% complete
99.9% complete
99.8% complete
Downloading https://repo1.maven.org/maven2/.index/nexus-maven-repository-index.gz
before (http/get ...)
(:status :headers :body :request-time :trace-redirects :orig-content-encoding)
{X-Cache HIT, HIT, Fastly-Debug-Digest 3c9855f6f96a7ecfc8c7b3eade9317c81d9b3d6597695b109b667afb5f660b9d, X-Timer S1455568360.439749,VS0,VE0, x-amz-meta-last-modified-epoch 1453670376328, Via [1.1 varnish 1.1 varnish], Content-Type application/x-gzip, Content-Length 226702600, Connection close, X-Checksum-MD5 e32b6c0d521bd9bda3f48c9b2348dd02, Accept-Ranges bytes, ETag "e32b6c0d521bd9bda3f48c9b2348dd02", X-Cache-Hits 0, 0, Date Mon, 15 Feb 2016 20:32:40 GMT, X-Checksum-SHA1 a9770a788708ba1504b3bd0f8db08934850ab006, Last-Modified Sun, 24 Jan 2016 21:19:36 GMT, X-Served-By cache-iad2121-IAD, cache-lcy1125-LCY}
status: 200
content-length: 226702600
100.0% complete
Updating the search index. This may take a few minutes...
Downloading https://clojars.org/repo/.index/nexus-maven-repository-index.properties
before (http/get ...)
(:status :headers :body :request-time :trace-redirects :orig-content-encoding)
{Server nginx, Content-Type text/plain, Strict-Transport-Security max-age=31536000, Connection close, Transfer-Encoding chunked, Expires Mon, 22 Feb 2016 20:36:58 GMT, Date Mon, 15 Feb 2016 20:36:58 GMT, Vary Accept-Encoding, Last-Modified Mon, 15 Feb 2016 20:05:35 GMT, Cache-Control max-age=604800}
status: 200
content-length nil
^C
```
It looks like the code printing the download progress may need to be changed to deal with a stream of unknown length. What I find strange, is that the code doesn't throw an exception when `Long/parseLong` gets called with a nil argument (it does throw when doing that in the REPL).

**Comment by ackalker** [comment] 2016-02-15 21:44
Oddly, getting the headers with `curl` *does* return a `Content-Length` header:

```sh
$ curl -I https://clojars.org/repo/.index/nexus-maven-repository-index.properties
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 15 Feb 2016 21:43:07 GMT
Content-Type: text/plain
Content-Length: 1852
Last-Modified: Mon, 15 Feb 2016 21:05:36 GMT
Connection: keep-alive
Vary: Accept-Encoding
Expires: Mon, 22 Feb 2016 21:43:07 GMT
Cache-Control: max-age=604800
Strict-Transport-Security: max-age=31536000
Accept-Ranges: bytes
```

**Comment by hyPiRion** [comment] 2016-02-15 23:15
Thanks for looking into this issue!

I'm guessing that the content length not throwing may just be caught higher up in the pipeline, causing the entire thing to stall. I haven't looked too deeply into it however.

Simulating clojars, I noticed that `clj-http` adds in `accept-encoding: gzip, deflate`, which seems to be the reason the content length is not sent over. Not sure how smart it is to remove that in general, but we could at least verify whether it would work without any content encoding.

We'd obviously like progress bars when it's possible create one, but the issue here is first and foremost to get search up and running again.

**Comment by pauldorman** [comment] 2016-02-16 01:09
Is this an acceptable workaround? (too chicken to make a pull request at this point):

```clojure
(defn- ext-printProgress [this]
  (let [state @(.state this)
        total-bytes (:total-bytes state)
        content-length (:content-length state)]
    (if (< 0 content-length)
      (let [progress (/ (* total-bytes 100.0) content-length)
            ending (if-not (== progress 100) "\r" "\n")]
        (printf "%.1f%% complete%s" progress ending))
      (printf "%d bytes downloaded\r" total-bytes))
    (flush)))
```

```clojure
(defn- http-resource-fetcher []
  (let [base-url (promise)
        stream (promise)]
    (proxy [ResourceFetcher] []
      ;; TODO: handle connect/disconnect properly
      (connect [id url]
        (deliver base-url url))
      (disconnect []
        (.close @stream))
      (^java.io.InputStream retrieve [name]
        (println "Downloading" (str @base-url "/" name))
        (let [r (http/get (str @base-url "/" name)
                          {:throw-exceptions false :as :stream})
              l (Long/parseLong (get-in r [:headers "content-length"] "0"))
              s (leiningen.search.extstream. (:body r) l)]
          (deliver stream s)
          s)))))
```

**Comment by gspringtech** [comment] 2016-02-25 03:45
I have the same problem. Is there a workaround - other than modifying the program as per pauldorman above?

**Comment by pauldorman** [comment] 2016-02-25 19:23
I'm happy to send you the uberjar if that would be helpful.

**Comment by hyPiRion** [comment] 2016-02-25 21:09
Oh, sorry for not replying to this – I must've lost it between other issues.

@pauldorman: Thanks for looking into this further; I am pretty sure the code you've written is good and working as intended. I'll see if I can test this out tonight or during tomorrow to verify though. And don't worry about making pull requests – we won't bite :)

**Comment by gspringtech** [comment] 2016-02-25 22:55
@pauldorman Thanks - but I will wait.

**Comment by pauldorman** [comment] 2016-02-26 01:52
Okay then, I'll try to stop being such a coward :)

**Comment by hyPiRion** [comment] 2016-02-26 14:49
Fixed by #2101

**Closed by hyPiRion** 2016-02-26 14:49 UTC
Labels: bug

**Comment by pbsladek** [comment] 2016-05-30 04:46
I'm getting the same error. Can we reopen this?
Leiningen 2.6.1 on Java 1.8.0_92

lein search ring
Updating the search index. This may take a few minutes...
Downloading https://clojars.org/repo/.index/nexus-maven-repository-index.properties
^\2016-05-29 21:27:20
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode):

"Index-BottleWarmer-clojars" #15 daemon prio=5 os_prio=31 tid=0x00007f9fcbdfe000 nid=0xb003 waiting on condition [0x000070000165e000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.apache.maven.index.context.DefaultIndexingContext$1.run(DefaultIndexingContext.java:1189)
	at java.lang.Thread.run(Thread.java:745)

"Index-BottleWarmer-central" #14 daemon prio=5 os_prio=31 tid=0x00007f9fcbc1a800 nid=0xae03 waiting on condition [0x000070000155b000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.apache.maven.index.context.DefaultIndexingContext$1.run(DefaultIndexingContext.java:1189)
	at java.lang.Thread.run(Thread.java:745)

"com.google.inject.internal.util.$Finalizer" #13 daemon prio=5 os_prio=31 tid=0x00007f9fcd3c1800 nid=0x7617 in Object.wait() [0x00007000013d5000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0f99d98> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c0f99d98> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at com.google.inject.internal.util.$Finalizer.run(Finalizer.java:143)
	at java.lang.Thread.run(Thread.java:745)

"AWT-AppKit" #11 daemon prio=5 os_prio=31 tid=0x00007f9fcc1b5800 nid=0x220b runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007f9fcb881000 nid=0x4803 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007f9fcb87e000 nid=0x4603 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007f9fcb87d800 nid=0x4403 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007f9fcd04e800 nid=0x4203 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007f9fcd04d800 nid=0x370f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007f9fcb864800 nid=0x3003 in Object.wait() [0x000070000092e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0017b78> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c0017b78> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007f9fcb804000 nid=0x2e03 in Object.wait() [0x000070000082b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c000ff90> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000006c000ff90> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=31 tid=0x00007f9fcb80a800 nid=0xb07 waiting on condition [0x0000700000213000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076d0164f8> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at clojure.core$promise$reify__7005.deref(core.clj:6823)
	at clojure.core$deref.invokeStatic(core.clj:2228)
	at clojure.core$deref.invoke(core.clj:2214)
	at leiningen.search$http_resource_fetcher$fn__5439.invoke(search.clj:98)
	at leiningen.search.proxy$java.lang.Object$ResourceFetcher$93824c0b.disconnect(Unknown Source)
	at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at leiningen.search$update_index.invokeStatic(search.clj:110)
	at leiningen.search$update_index.invoke(search.clj:109)
	at leiningen.search$search$fn__5504.invoke(search.clj:222)
	at leiningen.search$search.invokeStatic(search.clj:222)
	at leiningen.search$search.invoke(search.clj:193)
	at leiningen.search$search.invokeStatic(search.clj:208)
	at leiningen.search$search.invoke(search.clj:193)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$partial_task$fn__5829.doInvoke(main.clj:272)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$apply.invoke(core.clj:641)
	at leiningen.core.main$apply_task.invokeStatic(main.clj:322)
	at leiningen.core.main$apply_task.invoke(main.clj:308)
	at leiningen.core.main$resolve_and_apply.invokeStatic(main.clj:328)
	at leiningen.core.main$resolve_and_apply.invoke(main.clj:324)
	at leiningen.core.main$_main$fn__5895.invoke(main.clj:401)
	at leiningen.core.main$_main.invokeStatic(main.clj:394)
	at leiningen.core.main$_main.doInvoke(main.clj:391)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.main$main_opt.invokeStatic(main.clj:314)
	at clojure.main$main_opt.invoke(main.clj:310)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at clojure.lang.Var.invoke(Var.java:394)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)

"VM Thread" os_prio=31 tid=0x00007f9fcc802800 nid=0x2c03 runnable

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007f9fcb817800 nid=0x1607 runnable

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007f9fcb818800 nid=0x2603 runnable

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007f9fcb819000 nid=0x2803 runnable

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007f9fcb819800 nid=0x2a03 runnable

"VM Periodic Task Thread" os_prio=31 tid=0x00007f9fcd0a1000 nid=0x4a03 waiting on condition

JNI global references: 259

Heap
 PSYoungGen      total 454144K, used 57198K [0x000000076ab00000, 0x0000000792380000, 0x00000007c0000000)
  eden space 420864K, 13% used [0x000000076ab00000,0x000000076e2dba30,0x0000000784600000)
  from space 33280K, 0% used [0x0000000784600000,0x0000000784600000,0x0000000786680000)
  to   space 36352K, 0% used [0x0000000790000000,0x0000000790000000,0x0000000792380000)
 ParOldGen       total 257024K, used 41476K [0x00000006c0000000, 0x00000006cfb00000, 0x000000076ab00000)
  object space 257024K, 16% used [0x00000006c0000000,0x00000006c2881030,0x00000006cfb00000)
 Metaspace       used 51883K, capacity 61640K, committed 61848K, reserved 1095680K
  class space    used 11981K, capacity 15420K, committed 15536K, reserved 1048576K

**Comment by chmeee** [comment] 2016-05-31 04:45
Same issue for me on Arch: 'aur/leiningen 1:2.6.1-3' and 'extra/jdk8-openjdk 8.u92-1'.

**Comment by alexakarpov** [comment] 2016-06-03 23:29
also seeing this on Ubuntu/Leiningen 2.6.1 on Java 1.8.0_74 Java HotSpot(TM) 64-Bit Server VM

**Comment by kat-co** [comment] 2016-06-11 01:53
Also seeing on Ubuntu/Leiningen 2.6.1 on Java 1.8.0_91 Java HotSpot(TM) 64-Bit Server VM

**Comment by ChromoX** [comment] 2016-06-12 01:46
Seeing this on Mac OS X 10.11.5/Leiningen 2.6.1 on Java 1.8.0_74 Java HotSpot(TM) 64-Bit Server VM

**Comment by pauldorman** [comment] 2016-06-19 22:29
I was going to have a look into this but things are working fine with the 2.6.2-SNAPSHOT. Is there still a problem for 2.6.1? I can't easily check as the snapshot release updated all my indexes and my 2.6.1 version doesn't currently need to update (afaik).

**Comment by hyPiRion** [comment] 2016-06-20 08:04
Sorry for the radio silence here, @pauldorman's fix (#2101) is working as intended, it just hasn't been deployed yet.

**Comment by MattDMo** [comment] 2016-06-27 21:16
I may be missing something, but how does one use the current code in master? I downloaded `https://github.com/technomancy/leiningen/blob/master/bin/lein`, made it executable, and ran it, but got this error:

```
$ lein
Downloading Leiningen to /home/mattdmo/.lein/self-installs/leiningen-2.6.2-SNAPSHOT-standalone.jar now...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Failed to download https://github.com/technomancy/leiningen/releases/download/2.6.2-SNAPSHOT/leiningen-2.6.2-SNAPSHOT-standalone.zip (exit code 22)
It's possible your HTTP client's certificate store does not have the
correct certificate authority needed. This is often caused by an
out-of-date version of libssl. It's also possible that you're behind a
firewall and haven't set HTTP_PROXY and HTTPS_PROXY.
```

I'm not behind a firewall or proxy, my certificates are fine, and libssl is up to date. lein v2.6.1 works just fine, except for the search feature, which is how I found myself here. I suspect it's because there's no `2.6.2-SNAPSHOT` release. Do I need to clone the whole repo and run `lein` from within it?

**Comment by cprice404** [comment] 2016-06-27 21:24
@MattDMo check out the [CONTRIBUTING.md](https://github.com/technomancy/leiningen/blob/5562b5e98a04450de8d25b090a1e5e8e31d647a1/CONTRIBUTING.md#bootstrapping) docs; you probably just need to go into the `leiningen-core` directory and run `lein bootstrap`.

**Comment by MattDMo** [comment] 2016-06-27 21:31
@cprice404 Ah, the one file I *didn't* read :grimacing: I misread the name as CONTRIBUTORS.md and figured it was just a list of names. Many thanks, I think I'm all set now.
