### ISSUE TITLE
`lein repl` fails with clojure 1.10.3

### ISSUE THREAD

**Issue by gs** [technomancy/leiningen#2749] opened 2021-06-08 06:56 UTC
**Initial debugging steps**
Before creating a report, _especially_ around exceptions being thrown when running Leiningen, please check if the error still occurs after:

- [ x] Updating to using the latest released version of Leiningen (`lein upgrade`).
- [ x] Moving your `~/.lein/profiles.clj` (if present) out of the way. This contains third-party dependencies and plugins that can cause problems inside Leiningen.
- [ x] Updating any old versions of plugins in your `project.clj`, especially if the problem is with a plugin not working. Old versions of plugins like nREPL and CIDER (as well as others) can cause problems with newer versions of Leiningen.
- [x ] (If you are using Java 9 or newer), updating your dependencies to their most recent versions. Recent JDK's have introduced changes which can break some Clojure libraries.

**Describe the bug**
`lein repl` fails after new project generation - with clojure 1.10.3

**To Reproduce**
1. lein new beaver
2. cd beaver ; lein repl
3. https://gist.github.com/gs/9b231a5a416884d781dbbd8a37aba8fd

**Actual behavior**
lein repl - should work

**Expected behavior**
lein shoud start repl

**Link to sample project**
If relevant, please provide a link to a project or a `project.clj` that others can use to help debug the issue.

**Environment**
- Leiningen Version: 2.9.6
- Leiningen installation method: homebrew
- JDK Version: 1.8.0_101
- OS:  macos

** Solution
As I'm using the clojure 1.10.3 - the `project.clj` is generated with `1.10.1` that is why the exception happens. 
Shall we by default create `project.clj` with newest version?

**Comment by technomancy** [comment] 2021-06-10 16:29
I can't reproduce this problem; the repl launches fine for me whether it's 1.10.1 or 1.10.3.

**Comment by technomancy** [comment] 2021-09-01 00:44
Closing this as it is not reproducible; feel free to reopen if there are more details.

**Closed by technomancy** 2021-09-01 00:44 UTC
