### ISSUE TITLE
No :main namespace specified in project.clj.

### ISSUE THREAD

**Issue by djuwa4** [technomancy/leiningen#2689] opened 2020-06-18 14:08 UTC
Hello! I do everything according to the instructions:
1) Download the lein script (or on Windows lein.bat)
2) Place it on your $PATH where your shell can find it (eg. ~/bin)
3) Set it to be executable (chmod a+x ~/bin/lein)
4) After running the downloaded script: ./lein run
I get an error:
No :main namespace specified in project.clj. - No :main namespace specified in project.clj.

When I try to build our project by doing: lein run, i get errors related to access through a proxy server:
Could not transfer artifact reagent:reagent:pom:0.8.1 from/to central (https://repo1.maven.org/maven2/): proxy.domain.com
Could not transfer artifact re-frame:re-frame:pom:0.10.8 from/to central (https://repo1.maven.org/maven2/): proxy.domain.com

This is an example of errors, there are many similar errors. And yes, we have to work through a corporate proxy server. /etc/environment - configured correctly

I ask you to help solve these problems.

**Environment**
- Leiningen Version and JDK Version: Leiningen 2.9.3 on Java 1.8.0_232 OpenJDK 64-Bit Server VM
- OS: Debian

**Comment by djuwa4** [comment] 2020-06-19 07:35
I solved proxy related problems. But, I still want to understand the cause of the error: No :main namespace specified in project.clj

In any case, this problem did not prevent the application from being built.

**Comment by glts** [comment] 2020-06-19 16:12
In step 4 you say `./lein run`. This is not how Leiningen is usually invoked. Usually we make sure the directory with the `lein` script is on the shell's search path; then the command is just `lein run`. Does this make a difference?

**Comment by technomancy** [comment] 2020-06-21 20:48
> I solved proxy related problems. But, I still want to understand the cause of the error: No :main namespace specified in project.clj

The problem is undoubtedly something to do with your project.clj, but it's impossible to say more without seeing it.

> In any case, this problem did not prevent the application from being built.

Sure, but the point of `lein run` is not to build the application; it's to run it.

**Comment by technomancy** [comment] 2020-07-08 19:08
Going to close this since there isn't enough detail to be actionable, but we can reopen if more info is provided.

**Closed by technomancy** 2020-07-08 19:08 UTC

**Comment by djuwa4** [comment] 2020-07-20 07:36
> Going to close this since there isn't enough detail to be actionable, but we can reopen if more info is provided.

Yes, you can close! Many thanks to everyone!
