### ISSUE TITLE
lein upgrade still producing checksum errors for 2.9.1 to 2.9.2 upgrade

### ISSUE THREAD

**Issue by stephensmith9** [technomancy/leiningen#2663] opened 2020-03-08 15:34 UTC
https://github.com/technomancy/leiningen/issues/2662#issuecomment-595574261

Tried the above fix but that gives:

Failed to download https://github.com/technomancy/leiningen/releases/download/2.9.3.SNAPSHOT/leiningen-2.9.3.SNAPSHOT-standalone.zip (exit code 22)

There is no 2.9.3.SNAPSHOT folder that I can see?

I had lein 2.9.1 installed, simply tried 'lein upgrade' and got the same checksum error that was reported in issue 2662.

On MacOS 10.13.6, running java 11.0.6

**Comment by technomancy** [comment] 2020-03-08 16:53
This is another duplicate of #2658 

Going to reset the stable branch back until 2.9.3 is out with a fix.

**Closed by technomancy** 2020-03-08 16:53 UTC
