### ISSUE TITLE
Possible regression in mirrored repo project config 

### ISSUE THREAD

**Issue by mrrodriguez** [technomancy/leiningen#1876] opened 2015-04-08 17:37 UTC
I'm getting this error https://www.refheap.com/99369 with leiningen 2.5.1.

It looks related to https://github.com/heroku/heroku-buildpack-clojure/issues/31,
which was supposedly fixed https://github.com/heroku/heroku-buildpack-clojure/issues/31#issuecomment-45946240 in version 2.4.1.

I rolled back my leiningen to 2.5.0 and the mirror error goes away.

It looks like this is a potential regression in 2.5.1.

**Comment by weissjeffm** [comment] 2016-05-31 21:10
I seem to be having the same issue with lein 2.5.3. Any suggestion or workaround would be much appreciated!

**Comment by glts** [comment] 2019-05-17 21:44
This is about a regression, but actually I’m unable to see any info about the bug here. If we cannot reproduce this then I think we can close it.

**Closed** 2019-05-20 22:58 UTC
Labels: bug
