### ISSUE TITLE
Atomic releases

### ISSUE THREAD

**Issue by danielcompton** [technomancy/leiningen#2109] opened 2016-03-10 20:06 UTC
When using `lein release`, if any of the steps fail, then you can be left with a partially released project. It would be good if leiningen rolled back the changes that it made. This is difficult/impossible in the general case, but just rolling back git commits and tags would cover the 90% use case, for me at least. OTOH this might make things even worse depending on where the user got to in a deploy step.

**Comment by hyPiRion** [comment] 2016-03-13 19:39
This seems related to #2064.

Now that Clojars deployment is atomic, this seems more sensible. Perhaps this/#2064 could be started by telling you how you can manually revert a deploy step, then we can enhance that to actually attempt to revert it later on.

**Comment by timgilbert** [comment] 2016-04-06 19:40
At a minimum, `lein vcs assert-committed` should bail out if it discovers that there are uncommitted changes in the working copy. Right now it tells you changes are not checked in and then goes ahead with the deploy anyways, making its usefulness dubious at best.

**Comment by technomancy** [comment] 2017-05-22 19:03
Closing this as a duplicate of #2064.

@timgilbert Also, `lein vcs assert-committed` does call `abort`, so it does bail. If you're seeing it do otherwise, that's a serious bug that should be reported separately, but I can't reproduce it.

**Closed by technomancy** 2017-05-22 19:03 UTC
