### ISSUE TITLE
lein repl - no tab completion/autocomplete

### ISSUE THREAD

**Issue by ghost** [technomancy/leiningen#1922] opened 2015-06-23 23:51 UTC
## Description

For some strange reason the REPL does not enable tab-completion/autocompletion on this box. I've attempted installation via `brew install leinigen` and [leiningen's self-install script](https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein), both to no avail. I'm still very new to leiningen/clojure and having difficulty identifying a path to resolution. 
## Meiningen and JDK Version

Leiningen 2.5.1 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM
## Computer

Macbook Pro 13 (2015)
OS X Yosemite (10.10.3)
zsh 5.0.5 (x86_64-apple-darwin14.0)

**Comment by hyPiRion** [comment] 2015-11-03 18:09
Is this still an issue? As I don't have a macbook, I am unable to reproduce this.

**Comment by winks** [comment] 2015-11-03 18:17
Trying to repro tomorrow when I can steal a coworker's ~~cookies~~ macbook for a sec.

**Comment by winks** [comment] 2015-11-04 11:51
Could not reproduce with these:

```
>>> ==> Pouring leiningen-2.5.3.el_capitan.bottle.tar.gz
java version "1.6.0_65"`
zsh 5.0.8 (x86_64-apple-darwin15.0)
```

But it could still be a JDK 8 issue.

**Comment by hyPiRion** [comment] 2015-11-23 19:26
I'll see if I can manage to ~~steal~~ borrow a macbook at work tomorrow, and see if I am able to reproduce this on jdk 1.8.x.

It's a bit strange that this is not a bigger issue though.

**Comment by glts** [comment] 2019-05-12 15:11
Passing by … years have passed, no one has been able to repro. Can we close this?

**Comment by technomancy** [comment] 2019-05-13 04:31
Yes, no reason to keep it open if no actionable information has arisen.

**Closed by technomancy** 2019-05-13 04:31 UTC
Labels: bug
