### ISSUE TITLE
dev plugins exclusions don't seem to be working

### ISSUE THREAD

**Issue by shmish111** [technomancy/leiningen#2066] opened 2016-01-13 14:35 UTC
in my project file I have

``` clj
:profiles {:dev {:dependencies [[javax.servlet/servlet-api "2.5"]
                                  [ring-mock "0.1.5"]
                                  [org.clojure/data.json "0.2.6"]
                                  [midje "1.8.3"]]
                   :plugins [[cider/cider-nrepl "0.10.1" :exclusions [org.clojure/tools.nrepl]]]}}
```

when I run `lein deps :tree`

```
Possibly confusing dependencies found:
[org.clojure/tools.nrepl "0.2.10" :exclusions [org.clojure/clojure]]
 overrides
[cider/cider-nrepl "0.10.1"] -> [org.clojure/tools.nrepl "0.2.12" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[cider/cider-nrepl "0.10.1" :exclusions [org.clojure/tools.nrepl]]

Aborting due to :pedantic? :abort
```

I've also tried moving the cider plugin to my .lein profiles with the same result, it seems to just be ignoring the exclusion. Am I making a stupid mistake here? I copied and pasted the dependency vector from the output of lein to be sure it wasn't a type. Also, cider seems to work fine if I get rid of `:pedantic? :abort`

**Comment by hyPiRion** [comment] 2016-01-18 17:25
Yeah, that seems like a bug. 

If it's possible to get a fully reproducible case (full `project.clj`) to verify that it's a bug, I'll happily take patches to fix this.

**Comment by shmish111** [comment] 2016-01-21 12:08
```clj
(defproject plugin-deps "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]]
  :pedantic? :abort
  :plugins [[cider/cider-nrepl "0.10.1" :exclusions [org.clojure/tools.nrepl]]]
```

I had a look at the lein source code but I struggled to work out what's going on, I would need to spend quite some time looking into it which I don't really have right now. I guess it wouldn't be too difficult for someone who knows how all this works but I'll try if I get the chance.

**Comment by hyPiRion** [comment] 2016-01-21 12:24
Thanks for the reproducible case :)

And no worries about providing patches. It was more of a confirmation that pull requests which solves this issue will be merged in.

I'll probably have a look at this one when I get the time to do so either way, if it's small might even get it in for 2.6.0.

**Comment by neverfox** [comment] 2016-04-09 16:06
Yeah, this is frustrating when dealing with any pedantic project, as I have to remove all my usual plugins that might have `org.clojure/clojure` or something similarly common in them.

**Comment by kumarshantanu** [comment] 2017-05-22 11:01
+1 This issue is a blocker for using `:pedantic? :abort` entry in `project.clj`.

**Comment by glts** [comment] 2017-08-12 10:04
Can anyone confirm this is still a problem? I can reproduce this on 2.5.3 but not on 2.7.1 or master.

**Comment by technomancy** [comment] 2017-08-15 05:44
Yeah it looks like this is not an issue with master.

**Closed by technomancy** 2017-08-15 05:44 UTC
Labels: bug
