### ISSUE TITLE
:mirrors in :user profile in ~/.lein/profiles.clj not honored by the new task when resolving templates

### ISSUE THREAD

**Issue by tobias** [technomancy/leiningen#2058] opened 2016-01-03 16:01 UTC
To recreate:
1. blackhole clojars.org (by adding `127.0.0.1 clojars.org` to `/etc/hosts`)
2. `rm -rf ~/.m2/repository/luminus/lein-template`
3. add a mirror configuration to `~/.lein/profiles.clj`:
   
   ``` clojure
   :mirrors {#"clojars" {:name "clojars mirror"
                         :url "https://clojars-mirror.tcrawley.org/repo/"}}
   ```
4. `lein new luminus foo`

You should see:

```
$ lein new luminus foo
Failed to resolve version for luminus:lein-template:jar:RELEASE: Could not find metadata luminus:lein-template/maven-metadata.xml in local (/home/tcrawley/.m2/repository)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Could not find template luminus on the classpath.
```

From a brief reading of the code in `new.clj`, the mirrors are being passed to aether: https://github.com/technomancy/leiningen/tree/2.5.3/src/leiningen/new.clj#L27

which makes me think that either the :user profile isn't being properly loaded, or something about the request is causing aether to ignore the mirror?

This may be the cause of the issue reported in #2057 and clojars/clojars-web#451.

**Comment by cprice404** [comment] 2016-07-19 22:21
It seems like the reproducer here is no longer valid, because (presumably) the luminus template has been pushed to the public clojars?  I'm looking for an easy reproducer for all of these issues about the `~/.lein/profiles.clj` but if I run `lein new luminus foo` without setting up that mirror configuration anywhere, it works fine.

**Comment by tobias** [comment] 2016-07-19 23:34
@cprice404 did you point clojars.org to 127.0.0.1 in `/etc/hosts` from step 1? That should mimic clojars being down, since that was the case that exposed this issue. If clojars.org is unavailable, it won't matter if the luminus template is on clojars.org or not. If, after disabling clojars, `lein new luminus foo` works, then it must be pulling from the mirror, which would mean this issue has already been fixed I guess.

**Comment by cprice404** [comment] 2016-07-20 00:18
@tobias nope, missed that, thanks.

**Comment by tobias** [comment] 2016-07-20 00:25
My pleasure, let me know if you need anything else.

**Comment by cprice404** [comment] 2016-07-20 00:43
After hacking `/etc/hosts`, running the master branch from source, what I see is:

1. if I put the mirrors configuration in a profile *other than* `:user` (e.g. `:foo`), lein doesn't seem to use it even if I say `with-profile foo`.
2. if I put the mirrors configuration in the `:user` profile, it successfully downloads the template jar from the mirror (and then I get some `NumberFormatException` from the `luminus` code itself, which I presume is wholly unrelated).

So... my guess would appear that this probably is *not* related to #2057, but that there is a separate bug here that prevents `new` from honoring `with-profile`?

Might be good for someone else to try to repro with the mirrors in the `:user` profile and confirm that it works for them.  The original ticket description doesn't explicitly state which profile the `:mirrors` were being added to?

**Comment by cprice404** [comment] 2016-07-20 00:48
mirrors in the `:user` profile seem to fix this reproducer for me even on lein 2.5.3... confused :)

**Comment by tobias** [comment] 2016-07-20 18:08
I can only recreate this with 2.5.1, so it's likely that's the version I was running when I ran in to this issue (I recall a bug in 2.5.3 that caused me to stay on 2.5.1 for a while). So I think it's safe to call this fixed, at least for the `:user` profile (that's where I was putting the `:mirrors`).

**Comment by tobias** [comment] 2016-07-20 18:08
I didn't mean to close it myself :)

**Comment by jiacai2050** [comment] 2020-06-07 03:23
It seems this issue still exists in 2.9.3, but for `:plugin-repositories`, not `:mirrors`.

```
$ lein new cljs-start wonderful-lib
:repositories detected in user-level profiles! [:user]
See https://github.com/technomancy/leiningen/wiki/Repeatability
Could not find template cljs-start on the classpath.
```

**Comment by cmal** [comment] 2022-03-19 01:56
same problem

**Comment by technomancy** [comment] 2022-04-05 23:51
Unfortunately profiles can't be merged before plugins, because plugins can contain profiles.

**Closed by technomancy** 2022-04-05 23:51 UTC
