### ISSUE TITLE
lein 2.6.1 not work behind proxy

### ISSUE THREAD

**Issue by sctianwei** [technomancy/leiningen#2151] opened 2016-05-26 08:29 UTC
lein 2.6.1 cannot download dependence while running behind proxy.
I've set system property as:
http_proxy=http://username:password@proxy:port
https_proxy=http://username:password@proxy:port
and the error is: Not authorized by proxy , ReasonPhrase:Proxy Authentication Required. it seems that lein have used the host and port, but not use the username and password.

**Comment by winks** [comment] 2016-07-12 21:43
@sctianwei Sorry to get back so late only, but I just tried to reproduce this.

I am running leiningen 2.6.1 and used Squid 3.1.20-2.2+deb7u5 on Debian wheezy.

```
$ export http_proxy='correctuser:wrongpassword@myhost:3128'
$ lein repl

Could not transfer artifact lib-noir:lib-noir:pom:0.9.9 from/to central (https://repo1.maven.org/maven2/): Not authorized by proxy , ReasonPhrase:Proxy Authentication Required.
[...]
```
```
$ export http_proxy='correctuser:correctpassword@myhost:3128'
$ lein repl

Retrieving lib-noir/lib-noir/0.9.9/lib-noir-0.9.9.pom from clojars
[...]
```

```
$ export http_proxy='http://correctuser:correctpassword@myhost:3128'
$ lein repl

Retrieving lib-noir/lib-noir/0.9.9/lib-noir-0.9.9.pom from clojars
[...]
```

So my questions are:

a) have you tried without prefixing `http://`?
b) have you tried your http_proxy with any other CLI tool (maybe curl?)
c) which kind of proxy is that,

**Comment by hyPiRion** [comment] 2016-08-30 22:21
Since this issue has been open for quite some time without any response, and we're unable to reproduce it, I'm closing this one. Feel free to reopen if this still is an issue.

**Comment by amrfaissal** [comment] 2017-01-04 14:08
I'm facing the same issue here. I've set both `http_proxy` and `https_proxy` but no luck.
`wget` is working fine behind the proxy which I used to download the script itself.

**Comment by technomancy** [comment] 2017-05-22 17:15
Just for the record, I don't think any of the core developers have proxies like this available to test with, so we rely on users to investigate problems like this unfortunately.

**Closed** 2017-08-16 11:05 UTC
Labels: bug
